// Isolated synthetic accounts, file-backed state and captured transport. Never reads production.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {openState,emptyState} from '../../filmmaand-server/state.mjs';
import {createPlanningService} from '../../filmmaand-server/runtime/planning/service.mjs';
import {createApi} from '../../filmmaand-server/api.mjs';
import {createEventNotifications} from '../../filmmaand-server/event-notifications.mjs';
import {runCoordinationTick} from '../../filmmaand-server/date-coordination-tick.mjs';
export async function fixture(directory){await mkdir(directory,{recursive:true,mode:0o700});const file=directory+'/state.json';let clock='2026-09-10T10:00:00Z',code,cookie,account;
 const c=openState(emptyState());await createPlanningService({store:c.plans,adminToken:'isolated-admin'}).seed({id:'home-picker-lab',title:'Isolated date coordination',window:{start:'2026-09-01',end:'2026-09-30'},options:['a','b','c'].map(id=>({id,title:'Fictional '+id}))});const initial=c.export();c.close();await writeFile(file,JSON.stringify({etag:1,data:initial}),{mode:0o600});
 let lock=Promise.resolve();const store={async getWithMetadata(){await lock;const r=JSON.parse(await readFile(file,'utf8'));return {data:r.data,etag:String(r.etag)}},setJSON(key,data,{onlyIfMatch}){const task=lock.then(async()=>{const r=JSON.parse(await readFile(file,'utf8'));if(String(r.etag)!==onlyIfMatch)return {modified:false};await writeFile(file,JSON.stringify({etag:r.etag+1,data}),{mode:0o600});return {modified:true}});lock=task.then(()=>{},()=>{});return task}};
 const messages=[],mail=createEventNotifications({store,enabled:true,activatedAt:clock,allowAnyRecipient:true,now:()=>clock,send:async m=>{messages.push(m);return {providerId:'<captured@fixture.invalid>'}}});
 const organizerIds=[];const api=createApi({store,organizerIds,blobs:{},adminToken:'isolated-admin',origin:'http://localhost:4412',now:()=>clock,queueMail:async(c,m)=>{code=m.code},queueEvents:mail.queue});
 async function request(path,method='GET',body,headers={}){const r=await api(new Request('http://localhost:4412/filmmaand/api/'+path,{method,headers:{Origin:'http://localhost:4412',...headers},...(body?{body:JSON.stringify(body)}:{})}),{ip:'isolated-fixture'});return {status:r.status,body:await r.json(),headers:r.headers}}
 const challenge=await request('auth/code','POST',{email:'captured.date.coordination@gmail.com'});const login=await request('auth/verify','POST',{challengeId:challenge.body.challengeId,code});if(login.status!==200)throw Error(JSON.stringify(login.body));cookie=login.headers.get('set-cookie').split(';')[0];account=login.body.participant.id;organizerIds.push(account);const profile=await request('auth/profile','PUT',{expectedRevision:0,name:'Noor (voorbeeld)',animal:'otter',avatarId:4},{Cookie:cookie,'Idempotency-Key':'isolated-profile-key01'});if(profile.status!==200)throw Error(JSON.stringify(profile.body));
 const opened=await request('plans/home-picker-lab/date-poll','POST',{action:'open',mode:'availability',window:{start:'2026-09-12',end:'2026-09-14'},closesAt:'2026-09-11T10:00:00Z',choices:[]},{Authorization:'Bearer isolated-admin','Idempotency-Key':'isolated-poll-open01'});if(opened.status!==200)throw Error(JSON.stringify(opened.body));
 return {store,api,request,cookie,account,messages,mail,pollId:opened.body.datePoll.id,async tick(){const row=await store.getWithMetadata();const close=row.data.plans['home-picker-lab'].data.datePoll?.closesAt;if(close&&Date.parse(close)>=Date.parse(clock))clock=new Date(Date.parse(close)+60000).toISOString();return runCoordinationTick({store,queueEvents:mail.queue,now:()=>clock})}};
}
