// Date preference is independent of availability, film voting and the fixed programme.
const fail=(status,code,message)=>{throw Object.assign(new Error(message),{status,code})};
const iso=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
const strict=(b,keys)=>b&&typeof b==='object'&&!Array.isArray(b)&&Object.keys(b).every(k=>keys.includes(k));
const today=now=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));
export function ownDatePoll(p,a){const poll=p.datePoll;if(!poll)return {pollId:null,revision:0,date:null};const own=poll.votes?.[a];return {pollId:poll.id,revision:own?.revision||0,date:own?.date||null};}
export function publicDatePoll(p,me,display){const poll=p.datePoll;if(!poll)return null;const people=[];for(const [a,v]of Object.entries(poll.votes||{})){const profile=display(p,a);if(!profile||!iso(v.date))continue;people.push({name:profile.name,avatarId:profile.avatarId,date:v.date,...(a===me?{self:true}:{})});}people.sort((a,b)=>a.name.localeCompare(b.name,'nl'));const counts=new Map();for(const person of people)counts.set(person.date,(counts.get(person.date)||0)+1);const max=Math.max(0,...counts.values());return {id:poll.id,status:poll.status,window:{...poll.window},choices:[...poll.choices],people,leaderDates:[...counts].filter(([,count])=>count===max).map(([date])=>date).sort(),voteCount:people.length};}
export function setDatePoll(p,b,{id,now}){if(!strict(b,['action','pollId','window','choices']))fail(400,'date_poll','Ongeldige datumpoll.');
 if(b.action==='close'){if(!strict(b,['action','pollId'])||!p.datePoll||b.pollId!==p.datePoll.id)fail(409,'date_poll_changed','Deze datumpoll is veranderd.');p.datePoll.status='closed';return;}
 if(b.action!=='open'||Object.hasOwn(b,'pollId'))fail(400,'date_poll','Kies een geldige pollhandeling.');if(p.datePoll?.status==='open')fail(409,'date_poll_open','Sluit eerst de huidige datumpoll.');
 if(!strict(b.window,['start','end'])||!iso(b.window.start)||!iso(b.window.end)||b.window.start>b.window.end||b.window.start<p.window.start||b.window.end>p.window.end||b.window.end<today(now))fail(400,'date_poll_window','Kies een toekomstige periode binnen de planning.');
 if(!Array.isArray(b.choices)||new Set(b.choices).size!==b.choices.length||b.choices.some(id=>!p.options.some(o=>o.id===id)))fail(400,'date_poll_choices','Kies bestaande films of laat de filmkeuze open.');
 p.datePoll={id,status:'open',window:{...b.window},choices:[...b.choices],votes:{},openedAt:now};
}
export function writeDatePoll(p,a,b,now){if(!strict(b,['pollId','revision','date']))fail(400,'date_poll','Ongeldige datumstem.');const poll=p.datePoll;if(!poll||b.pollId!==poll.id)fail(409,'date_poll_changed','Deze datumpoll is veranderd.');if(poll.status!=='open')fail(409,'date_poll_closed','Deze datumpoll is gesloten.');const own=ownDatePoll(p,a);if(!Number.isInteger(b.revision)||b.revision<0)fail(400,'revision','Een versienummer ontbreekt.');if(b.revision!==own.revision)fail(409,'revision_conflict','Je datumstem is elders veranderd.');if(!iso(b.date)||b.date<poll.window.start||b.date>poll.window.end||b.date<today(now))fail(400,'date_poll_date','Kies een komende dag binnen deze poll.');poll.votes[a]={revision:own.revision+1,date:b.date,updatedAt:now};return ownDatePoll(p,a);}
