import {createHash,timingSafeEqual} from 'node:crypto';
import {roundLifecycle,rankedSelection,guardRoundWrite,changeRound,freezeNextSelection} from './round-lifecycle.mjs';
import {isSessionToken,isAnonymousBearer,isParticipantActor} from './auth/credentials.mjs';
const fail=(status,code,message,details)=>{throw Object.assign(new Error(message),{status,code,details})};
const hash=x=>createHash('sha256').update(x).digest('hex');
const date=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x;
const days=(a,b)=>{const out=[];for(let d=Date.parse(a);d<=Date.parse(b);d+=864e5)out.push(new Date(d).toISOString().slice(0,10));return out};
const plain=(s,max)=>typeof s==='string'&&s.length<=max&&!/[<>\x00-\x1f]/.test(s);
const messageText=s=>typeof s==='string'&&s.length<=500&&!/[<>\x00-\x09\x0b\x0c\x0e-\x1f]/.test(s);
const themeArt=value=>typeof value==='string'&&/^https:\/\/(?:m\.media-amazon\.com\/images\/M\/|image\.tmdb\.org\/t\/p\/)[A-Za-z0-9.@%_/-]+$/.test(value)?value:null;
const themeMovie=m=>({id:m.id,title:m.title,year:m.year,...(m.runtime?{runtime:m.runtime}:{}),poster:themeArt(m.posterFull)||themeArt(m.poster)||themeArt(m.metadataPoster),backdrop:themeArt(m.backdrop)});
const themeCover=m=>{const url=m?.poster||m?.backdrop;return url?{url,...(m.backdrop?{backdrop:m.backdrop}:{}),caption:'Beeld uit '+m.title+(m.year?' ('+m.year+')':'')}:null};
export function createPlanningService({store,adminToken,movieCatalogue=null,imageStore=null,programmeMovies={},avatarIds=Array.from({length:43},(_,i)=>i),now=()=>new Date().toISOString(),identity=null}){
 // Three disjoint credential namespaces, never a fallback: a session token ('fms_…') must resolve through identity or it is a
 // 401; only an exact anonymous bearer becomes the legacy sha256 actor. Without an identity service the anonymous path is unchanged.
 function actor(token){if(isSessionToken(token)){if(!identity)fail(401,'session_invalid','Log opnieuw in.',{clear:true});return identity.resolveActor(token)}if(!isAnonymousBearer(token))fail(401,'unauthorized','Je browsersleutel ontbreekt.');return hash(token)}
 // An anonymous key that was claimed into an account may only replay its exact receipts; everything else is 410.
 const claimedTo=(p,a)=>p.claimedBy?.[a]||null;
 function guard(p,a){if(claimedTo(p,a))fail(410,'claimed','Deze browsersleutel is overgezet naar je account. Log in om verder te gaan.',{clear:true})}
 // Public display identity: account profile for participants (follows profile edits), the per-plan snapshot for anonymous actors.
 const display=(p,a)=>identity?.publicProfile?.(a)??p.displayProfiles?.[a]?.recommender??null;
 function admin(token){if(!adminToken||!token||!timingSafeEqual(Buffer.from(hash(token)),Buffer.from(hash(adminToken))))fail(401,'unauthorized','Beheerderstoegang vereist.')}
 const responseDates=r=>Array.isArray(r.dates)?r.dates:r.start&&r.end?days(r.start,r.end):[];
 const own=(p,a)=>p.responses[a]?{...p.responses[a],dates:responseDates(p.responses[a])}:{revision:0,start:null,end:null,dates:[],choices:[],name:'',updatedAt:null};
 async function load(id){for(let n=0;n<40;n++){const row=await store.read(id);if(!row)fail(404,'not_found','Deze planning bestaat niet.');const p=row.data;if(!freezeNextSelection(p,now(),[...plannedIds(p),...(p.round?.shortlist||[])]))return row;p.version++;if(await store.compareAndSwap(id,row.etag,p))continue;}fail(503,'busy','De planning wordt bijgewerkt. Probeer opnieuw.')}
 async function loadFor(id,a){const row=await load(id);guard(row.data,a);return row}
 function ownerOf(p,o){if(o.kind!=='suggestion')return null;for(const [key,r]of Object.entries(p.receipts)){const split=key.indexOf(':');const a=key.slice(0,split),k=key.slice(split+1);if(r.result?.option?.id===o.id&&o.id==='suggestion-'+hash(a+':'+k).slice(0,20))return a;}return null}
 function profile(p,a){if(isParticipantActor(a))return {revision:0,recommender:display(p,a)};return p.displayProfiles?.[a]||{revision:0,recommender:null}}
 function validatedProfile(r){if(!r||!plain(r.name,32)||!r.name.trim()||!Number.isInteger(r.avatarId)||!avatarIds.includes(r.avatarId))fail(400,'profile','Kies een geldige naam en avatar.');return {name:r.name.trim(),avatarId:r.avatarId}}
 // Planned nights (organizer-set, any number) plus the legacy single confirmation, projected together.
 const programmeOf=p=>[...(p.programme||[]),...(p.confirmation?[{id:'confirmation',...p.confirmation}]:[])];
 const plannedIds=p=>new Set(programmeOf(p).flatMap(n=>n.choices));
 const amsterdam=iso=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam'}).format(new Date(iso));
 function validStart(p,s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(s)||!Number.isFinite(Date.parse(s))||amsterdam(s)<p.window.start||amsterdam(s)>p.window.end)fail(400,'event_time','Een geldige starttijd in UTC is vereist.');return new Date(s).toISOString()}
 function optionCountsOf(p){const optionCounts=Object.fromEntries(p.options.map(o=>[o.id,0]));for(const r of Object.values(p.responses))for(const id of r.choices)if(id in optionCounts)optionCounts[id]++;return optionCounts}
 function rankedContribution(response){const choices=[...new Set(response?.choices||[])],rank=[...new Set(response?.rankingOrder||[])].filter(id=>choices.includes(id));return Object.fromEntries(choices.map(id=>[id,rank.indexOf(id)>=0?Math.max(1,5-rank.indexOf(id)):1]));}
 function nextRoundOf(p,me){const selection=p.round?.nextSelection||{...rankedSelection(p,[...plannedIds(p),...roundOf(p).shortlist]),status:'collecting',sourceRoundId:roundOf(p).id,closesAt:p.round?.closesAt||null,frozenAt:null};return {rule:'rank-5-4-3-2-1',...selection,...(me?{ownPoints:rankedContribution(p.responses[me])}:{})};}
 // The finale shortlist: organizer-set, or derived from picker preferences and frozen at the first vote.
 function deriveShortlist(p){const planned=plannedIds(p),counts=optionCountsOf(p);return p.options.map((o,i)=>({id:o.id,i,count:counts[o.id]||0})).filter(x=>!planned.has(x.id)).sort((a,b)=>b.count-a.count||a.i-b.i).slice(0,3).map(x=>x.id)}
 function roundOf(p){const planned=plannedIds(p);const shortlist=(p.round?.shortlist||deriveShortlist(p)).filter(id=>p.options.some(o=>o.id===id));return {shortlist,...(p.roundSchedule?.date?{scheduledDate:p.roundSchedule.date}:{}),derived:p.round?p.round.derived!==false:true,excluded:[...planned],planned:shortlist.some(id=>planned.has(id)),...roundLifecycle(p,now(),shortlist.some(id=>planned.has(id)))}}
 const voter=(p,a)=>{const r=display(p,a);return r?{name:r.name,avatarId:r.avatarId}:{name:null,avatarId:null}};
 const ownVote=(p,a)=>{const v=p.votes?.[a];return v?{revision:v.revision,final:v.final??null,next:v.next??null,updatedAt:v.updatedAt}:{revision:0,final:null,next:null,updatedAt:null}};
 function tally(p,phase,eligible){const counts=Object.fromEntries(eligible.map(id=>[id,0])),voters=Object.fromEntries(eligible.map(id=>[id,[]]));let total=0;for(const [a,v] of Object.entries(p.votes||{})){const id=v[phase];if(id&&id in counts){counts[id]++;voters[id].push(voter(p,a));total++}}return {total,counts,voters}}
 // Anonymous until you vote: a phase's tally is only projected once the caller's own vote in that phase exists.
 function voteView(p,a){const round=roundOf(p),own=ownVote(p,a),nextEligible=p.options.map(o=>o.id).filter(id=>!round.shortlist.includes(id)&&!round.excluded.includes(id));return {round,own,serverTime:now(),final:own.final?tally(p,'final',round.shortlist):null,next:own.next?tally(p,'next',nextEligible):null}}
 // Date+film suggestions are independent of votes, availability and organizer programme.
 const ownProposal=(p,a)=>p.nightProposals?.[a]||{revision:0,optionId:null,date:null,updatedAt:null};
 function proposalView(p,a){const groups=new Map();for(const [owner,proposal] of Object.entries(p.nightProposals||{})){if(!proposal.optionId||!proposal.date)continue;const key=proposal.optionId+':'+proposal.date;let group=groups.get(key);if(!group){group={optionId:proposal.optionId,date:proposal.date,count:0,people:[]};groups.set(key,group)}group.count++;group.people.push(voter(p,owner));}return {own:ownProposal(p,a),proposals:[...groups.values()].sort((x,y)=>x.date.localeCompare(y.date)||x.optionId.localeCompare(y.optionId))};}
 // Explicitly public provisional leaders for a scheduled round; never expose counts or people here.
 function scheduledLeaders(p){const ids=roundOf(p).shortlist,counts=new Map(ids.map(id=>[id,0]));for(const v of Object.values(p.votes||{}))if(counts.has(v.final))counts.set(v.final,counts.get(v.final)+1);const max=Math.max(0,...counts.values());return max?ids.filter(id=>counts.get(id)===max):[]}
 function publicPlan(p,me=null){const optionCounts=optionCountsOf(p),dateCounts=Object.fromEntries(days(p.window.start,p.window.end).map(d=>[d,0])),dateOptions=Object.fromEntries(Object.keys(dateCounts).map(d=>[d,{...Object.fromEntries(p.options.map(o=>[o.id,0]))}]));for(const r of Object.values(p.responses)){for(const d of responseDates(r)){if(!(d in dateCounts))continue;dateCounts[d]++;for(const id of r.choices)if(id in dateOptions[d])dateOptions[d][id]++;}}
  const people=Object.entries(p.responses).map(([a,r])=>{const rec=display(p,a);return rec?{name:rec.name,avatarId:rec.avatarId,dates:responseDates(r),choices:r.choices.filter(id=>p.options.some(o=>o.id===id)),...(Array.isArray(r.rankingOrder)?{rankingOrder:r.rankingOrder.filter(id=>r.choices.includes(id)&&p.options.some(o=>o.id===id))}:{}),...(me&&a===me?{self:true}:{})}:null}).filter(Boolean).sort((x,y)=>x.name.localeCompare(y.name,'nl'));
  return{id:p.id,title:p.title,window:p.window,options:p.options.map(o=>{const a=ownerOf(p,o),owner=a&&(claimedTo(p,a)||a),r=a&&display(p,owner);let out=r&&(o.recommender||isParticipantActor(owner))?{...o,recommender:me&&owner===me?{...r,self:true}:r}:o;const art=o.movie?.id&&movieCatalogue?.get?movieCatalogue.get(o.movie.id):null;if(art&&(art.posterFull||art.poster||art.metadataPoster||art.backdrop))out={...out,movie:{...out.movie,poster:art.posterFull||art.poster||art.metadataPoster||null,backdrop:art.backdrop||null,overview:art.overview||'',overviewLanguage:art.overviewLanguage||null,metadataSource:art.metadataSource||null,metadataUrl:art.metadataUrl||null}};if(Array.isArray(o.movies)&&o.movies.length){out={...out,movies:o.movies.map(m=>{const fresh=movieCatalogue?.get?.(m.id);if(!fresh)return m;const art=themeMovie(fresh);return {...m,poster:art.poster||m.poster,backdrop:art.backdrop||m.backdrop}})};if(!o.image?.id){const image=themeCover(out.movies[0]);if(image)out.image=image;}}if(owner){const likers=Object.entries(p.responses).filter(([,response])=>response.choices.includes(o.id));out={...out,proposerOnlyLiker:likers.length===1&&(claimedTo(p,likers[0][0])||likers[0][0])===owner};}return out}),maxChoices:p.maxChoices,status:p.confirmation?'confirmed':'collecting',responseCount:Object.keys(p.responses).length,optionCounts,nextRound:nextRoundOf(p,me),dateCounts,dateOptions,confirmation:p.confirmation,programme:programmeOf(p),people,round:{...roundOf(p),...(p.roundSchedule?.date?{scheduledDate:p.roundSchedule.date,leaderIds:scheduledLeaders(p)}:{})},version:p.version,serverTime:now()}}
 async function mutate(id,a,key,payload,action){if(!/^[A-Za-z0-9_-]{16,100}$/.test(key||''))fail(400,'request_key','Een verzoekcode ontbreekt.');const receiptKey=a+':'+key,fingerprint=hash(JSON.stringify(payload));for(let n=0;n<40;n++){const row=await load(id),p=row.data,prior=p.receipts[receiptKey];if(prior){if(prior.fingerprint!==fingerprint)fail(409,'key_reused','Deze verzoekcode hoort bij andere gegevens.');return prior.result;}guard(p,a);if(Object.keys(p.receipts).length>=5000)fail(503,'receipt_limit','Deze planning kan nu geen wijzigingen verwerken.');freezeNextSelection(p,now(),[...plannedIds(p),...(p.round?.shortlist||[])]);const result=action(p);p.version++;p.receipts[receiptKey]={fingerprint,result};if(await store.compareAndSwap(id,row.etag,p))return result;}fail(503,'busy','De planning wordt bijgewerkt. Probeer opnieuw.')}
 return {
  async seed(plan){if(!date(plan.window?.start)||!date(plan.window?.end)||plan.window.end<plan.window.start||days(plan.window.start,plan.window.end).length>62)fail(400,'window','Ongeldig datumvenster.');if(!Array.isArray(plan.options)||!plan.options.length||new Set(plan.options.map(o=>o.id)).size!==plan.options.length)fail(400,'options','Ongeldige opties.');return store.compareAndSwap(plan.id,null,{...plan,maxChoices:plan.maxChoices||plan.options.length,responses:{},receipts:{},confirmation:null,version:1});},
  // Optional credential: a valid one marks the caller's own people[] entry and own suggestion credits with self:true.
  // Anything invalid is ignored — the public GET never fails on identity and its payload is otherwise identical.
  async get(id,token=null){const p=(await load(id)).data;let me=null;if(token){try{me=actor(token);if(claimedTo(p,me))me=null}catch{me=null}}if(movieCatalogue?.details){const ids=[...new Set(p.options.flatMap(o=>[o.movie?.id,o.movies?.[0]?.id]).filter(Boolean))];let next=0;await Promise.all(Array.from({length:Math.min(4,ids.length)},async()=>{while(next<ids.length)await movieCatalogue.details(ids[next++]).catch(()=>null)}));}const out=publicPlan(p,me);out.metadataVersion=hash(JSON.stringify(out.options.map(o=>[o.movie||null,o.movies||null,o.image||null]))).slice(0,16);return out},
  async own(id,token){const a=actor(token);return {response:own((await loadFor(id,a)).data,a),identity:{kind:isParticipantActor(a)?'account':'anonymous'}}},
  async getProfile(id,token){const a=actor(token);return {profile:profile((await loadFor(id,a)).data,a)}},
  async updateProfile(id,token,key,b){const a=actor(token);if(isParticipantActor(a))fail(409,'account_profile','Je naam en avatar horen bij je account en wijzig je daar.');return mutate(id,a,key,{operation:'display-profile',body:b},p=>{const previous=profile(p,a);if(b?.expectedRevision!==previous.revision)fail(409,'conflict','Je profiel is elders gewijzigd.',{profile:previous});const recommender=validatedProfile(b.recommender);const next={revision:previous.revision+1,recommender};(p.displayProfiles||={})[a]=next;return {profile:next};})},
  async uploadImage(id,token,b){const a=actor(token);if((await loadFor(id,a)).data.confirmation)fail(409,'confirmed','De planning is gesloten voor nieuwe voorstellen.');if(!imageStore)fail(503,'image','Afbeeldingen zijn niet beschikbaar.');return {image:await imageStore.put(a,b?.data)}},
  async suggest(id,token,key,b){const a=actor(token);if(b?.imageId!==undefined&&(!imageStore||!await imageStore.owned(a,b.imageId)))fail(400,'image','Voeg je eigen afbeelding opnieuw toe.');return mutate(id,a,key,{operation:'suggestion',body:b},p=>{
   if(p.confirmation)fail(409,'confirmed','De planning is gesloten voor nieuwe voorstellen.');
   if(!b||!messageText(b.detail??''))fail(400,'suggestion','Gebruik maximaal 500 tekens zonder opmaak.');
   let movie=null;if(b.movieId!==undefined){if(!/^tt\d{7,12}$/.test(b.movieId||''))fail(400,'movie','Kies een film uit de zoekresultaten.');if(!movieCatalogue)fail(503,'catalogue_unavailable','De filmcatalogus is tijdelijk niet beschikbaar.');movie=movieCatalogue.get(b.movieId);if(!movie)fail(400,'movie','Deze film staat niet in de catalogus.');}
   if(!movie&&(!plain(b.title,120)||!b.title.trim()))fail(400,'suggestion','Gebruik een titel van maximaal 120 tekens zonder opmaak.');
   let movies=null;if(b.movieIds!==undefined){if(b.movieId!==undefined||!Array.isArray(b.movieIds)||b.movieIds.length<1||b.movieIds.length>12||new Set(b.movieIds).size!==b.movieIds.length||b.movieIds.some(id=>typeof id!=='string'||!/^tt\d{7,12}$/.test(id)))fail(400,'movies','Kies maximaal 12 verschillende films voor je thema.');if(!movieCatalogue)fail(503,'catalogue_unavailable','De filmcatalogus is tijdelijk niet beschikbaar.');movies=b.movieIds.map(id=>{const m=movieCatalogue.get(id);if(!m)fail(400,'movie','Een film staat niet meer in de catalogus. Zoek deze opnieuw.');return themeMovie(m)});}
   let recommender=null;if(b.recommender!==undefined){const r=b.recommender;if(!r||!plain(r.name,32)||!r.name.trim()||!Number.isInteger(r.avatarId)||!avatarIds.includes(r.avatarId))fail(400,'profile','Kies een geldige naam en avatar.');recommender={name:r.name.trim(),avatarId:r.avatarId};}
   const title=movie?movie.title+' ('+movie.year+')':b.title.trim(),duplicate=p.options.find(o=>movie&&(o.movie?.id===movie.id||programmeMovies[o.id]?.includes(movie.id))||o.title.toLocaleLowerCase('nl')===title.toLocaleLowerCase('nl'));
   if(duplicate)fail(409,'duplicate','Dit voorstel staat al in de lijst.',{option:duplicate});if(p.options.length>=200)fail(409,'option_limit','De lijst met voorstellen is vol.');
   const option={id:'suggestion-'+hash(a+':'+key).slice(0,20),title,detail:(b.detail||'').trim(),kind:'suggestion',createdAt:now()};if(movie)option.movie={id:movie.id,title:movie.title,originalTitle:movie.originalTitle,year:movie.year,runtime:movie.runtime,genres:movie.genres,rating:movie.rating,votes:movie.votes,asOf:movie.asOf};if(recommender)option.recommender=recommender;if(movies){option.movies=movies;option.lineup=movies.map(m=>m.title);const image=themeCover(movies[0]);if(image)option.image=image;}
   if(b.imageId!==undefined){if(movie)fail(400,'image','Eigen afbeeldingen horen bij een eigen thema.');option.image={id:b.imageId,url:'/planning-api/images/'+b.imageId+'.webp'};}if(movie){const previous=own(p,a);if(previous.choices.length>=p.maxChoices)fail(409,'choices','Je favorietenlijst is vol. Maak eerst ruimte voor deze film.');p.responses[a]={...previous,revision:previous.revision+1,choices:[...previous.choices,option.id],updatedAt:now()};}p.options.push(option);return {option,...(movie?{autoLiked:true}:{})};})},
  async submit(id,token,key,b){const a=actor(token);return mutate(id,a,key,b,p=>{if(p.confirmation)fail(409,'confirmed','De avond is bevestigd. Nieuwe wijzigingen zijn gesloten.');const previous=own(p,a);if(b.expectedRevision!==previous.revision)fail(409,'conflict','Je voorkeuren zijn elders gewijzigd.',{response:previous});let selectedDates;if(Object.hasOwn(b,'dates')){if(!Array.isArray(b.dates)||b.dates.length>62||new Set(b.dates).size!==b.dates.length||b.dates.some(d=>!date(d)||d<p.window.start||d>p.window.end))fail(400,'dates','Kies geldige beschikbare dagen binnen de planning.');selectedDates=[...b.dates].sort()}else{if(!date(b.start)||!date(b.end)||b.start>b.end||b.start<p.window.start||b.end>p.window.end)fail(400,'dates','Kies een geldige periode binnen september.');selectedDates=days(b.start,b.end)};if(!Array.isArray(b.choices)||b.choices.length>p.maxChoices||new Set(b.choices).size!==b.choices.length||b.choices.some(id=>!p.options.some(o=>o.id===id)))fail(400,'choices','Selecteer geldige opties.');if(!plain(b.name??'',60))fail(400,'name','Gebruik maximaal 60 tekens zonder opmaak.');if(Object.hasOwn(b,'rankingOrder')&&(!Array.isArray(b.rankingOrder)||b.rankingOrder.length>b.choices.length||new Set(b.rankingOrder).size!==b.rankingOrder.length||b.rankingOrder.some(id=>!b.choices.includes(id))))fail(400,'ranking','Rangschik alleen films die je een hartje hebt gegeven.');const rankingOrder=Object.hasOwn(b,'rankingOrder')?b.rankingOrder:previous.rankingOrder;const response={revision:previous.revision+1,start:selectedDates[0]||null,end:selectedDates.at(-1)||null,dates:selectedDates,choices:[...b.choices],...(Array.isArray(rankingOrder)?{rankingOrder:rankingOrder.filter(id=>b.choices.includes(id))}:{}),name:(b.name||'').trim(),updatedAt:now()};p.responses[a]=response;return {response};})},
  async proposals(id,token){const a=actor(token);return proposalView((await loadFor(id,a)).data,a)},
  async proposeNight(id,token,key,b){const a=actor(token);return mutate(id,a,key,{operation:'night-proposal',body:b},p=>{
   const previous=ownProposal(p,a);
   if(!b||b.expectedRevision!==previous.revision)fail(409,'conflict','Je voorstel is elders gewijzigd.',{own:previous});
   const withdraw=b.optionId===null&&b.date===null;
   if(!withdraw){if(typeof b.optionId!=='string'||!p.options.some(o=>o.id===b.optionId))fail(400,'option','Kies een film uit de collectie.');if(!date(b.date)||b.date<p.window.start||b.date>p.window.end||b.date<=amsterdam(now()))fail(400,'date','Kies een toekomstige avond binnen de kalender.');}
   const proposal={revision:previous.revision+1,optionId:withdraw?null:b.optionId,date:withdraw?null:b.date,updatedAt:now()};
   (p.nightProposals||={})[a]=proposal;return proposalView(p,a);
  })},
  async voteView(id,token){const a=actor(token);return voteView((await loadFor(id,a)).data,a)},
  async vote(id,token,key,b){const a=actor(token);return mutate(id,a,key,{operation:'vote',body:b},p=>{
   if(!p.round)p.round={shortlist:deriveShortlist(p),derived:true,since:now()};
   const round=roundOf(p),previous=ownVote(p,a);
   guardRoundWrite(p,b,round);
   if(!b||b.expectedRevision!==previous.revision)fail(409,'conflict','Je stem is elders gewijzigd.',{own:previous});
   if(round.planned)fail(409,'planned','Deze filmavond is al gepland.');
   const next={...previous};
   if(Object.hasOwn(b,'final')){if(b.final!==null&&!round.shortlist.includes(b.final))fail(400,'vote','Kies een van de drie films.');next.final=b.final}
   if(Object.hasOwn(b,'next')){if(b.next!==null&&(!p.options.some(o=>o.id===b.next)||round.shortlist.includes(b.next)||round.excluded.includes(b.next)))fail(400,'vote','Kies een film die nog niet in de finale of het programma staat.');next.next=b.next}
   next.revision=previous.revision+1;next.updatedAt=now();(p.votes||={})[a]=next;return voteView(p,a);})},
  async setRound(id,token,key,b){admin(token);return mutate(id,'admin',key,{operation:'round',body:b},p=>{
   if(b?.action){const round=roundOf(p);changeRound(p,b,{now:now(),key,round,excluded:[...plannedIds(p),...round.shortlist]});return {round:roundOf(p),nextRound:nextRoundOf(p),serverTime:now()};}
   if(p.round?.lifecycle||Object.values(p.votes||{}).some(v=>v.final||v.next))fail(409,'round_lifecycle','Gebruik de rondehandelingen; bestaande stemmen blijven bewaard.');
   const planned=plannedIds(p);if(!Array.isArray(b?.shortlist)||b.shortlist.length!==3||new Set(b.shortlist).size!==3||b.shortlist.some(x=>!p.options.some(o=>o.id===x)||planned.has(x)))fail(400,'shortlist','Kies drie verschillende, nog niet geplande opties.');p.round={id:'round-'+hash(id+':'+key).slice(0,20),revision:0,shortlist:[...b.shortlist],derived:false,since:now()};return {round:roundOf(p)};
  })},
  // A date for the open round is not a programme decision and never selects/locks a film.
  async scheduleRound(id,token,key,b){admin(token);return mutate(id,'admin',key,{operation:'round-date',body:b},p=>{if(p.round?.lifecycle&&roundOf(p).status!=='open')fail(409,'round_closed','De datum van een gesloten ronde kan niet worden gewijzigd.');if(b?.date!==null&&(!date(b?.date)||b.date<p.window.start||b.date>p.window.end))fail(400,'round_date','Kies een geldige datum binnen deze maand.');if(b.date===null)delete p.roundSchedule;else p.roundSchedule={date:b.date};return {round:roundOf(p)};})},
  async planNight(id,token,key,b){admin(token);return mutate(id,'admin',key,{operation:'programme',body:b},p=>{
   const pending=b?.selection==='pending';
   // This append-only contract has no update/transition operation.
   if(Object.hasOwn(b||{},'nightId'))fail(400,'programme_transition','Bestaande filmavonden wijzigen wordt niet ondersteund.');
   const validChoices=()=>Array.isArray(b?.choices)&&b.choices.length>0&&new Set(b.choices).size===b.choices.length&&b.choices.every(id=>p.options.some(o=>o.id===id));
   if(Object.hasOwn(b||{},'selection')&&!pending)fail(400,'selection','Gebruik een expliciete open filmkeuze of kies films voor een nieuwe avond.');
   // Pending is explicit and independent of any round, including a round on the same date.
   if(pending&&Object.keys(b).some(k=>!['selection','choices','scheduledDate','startsAt'].includes(k)))fail(400,'selection','Een open filmavond heeft alleen een datum of tijd en nog geen films of stemronde.');
   const dateOnly=Object.hasOwn(b||{},'scheduledDate');if(dateOnly&&Object.hasOwn(b,'startsAt'))fail(400,'event_time','Kies een datum of een starttijd, niet beide.');if(dateOnly&&(!date(b.scheduledDate)||b.scheduledDate<p.window.start||b.scheduledDate>p.window.end))fail(400,'event_time','Kies een geldige programmadatum.');const timing=dateOnly?{scheduledDate:b.scheduledDate}:{startsAt:validStart(p,b?.startsAt)};
   if(pending?(!Array.isArray(b.choices)||b.choices.length!==0):!validChoices())fail(400,'choices',pending?'Een open filmkeuze heeft een lege filmlijst.':'Kies geldige programmaopties.');
   const night={id:'night-'+hash(key+':'+(timing.startsAt||timing.scheduledDate)).slice(0,12),...timing,...(pending?{selection:'pending',choices:[]}:{choices:[...b.choices],confirmedAt:now()})};(p.programme||=[]).push(night);return {night};
  })},
  async confirm(id,token,key,b){admin(token);return mutate(id,'admin',key,b,p=>{if(p.confirmation)fail(409,'confirmed','De avond is al bevestigd.');if(typeof b.startsAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(b.startsAt)||!Number.isFinite(Date.parse(b.startsAt))||new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam'}).format(new Date(b.startsAt))<p.window.start||new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam'}).format(new Date(b.startsAt))>p.window.end)fail(400,'event_time','Een geldige starttijd in UTC is vereist.');if(!Array.isArray(b.choices)||!b.choices.length||new Set(b.choices).size!==b.choices.length||b.choices.some(id=>!p.options.some(o=>o.id===id)))fail(400,'choices','Kies geldige programmaopties.');p.confirmation={startsAt:new Date(b.startsAt).toISOString(),choices:b.choices,confirmedAt:now()};return {confirmation:p.confirmation};})}
 }
}
