import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,openState,transact} from './state.mjs';
import {createApi} from './api.mjs';
import {createPlanningService} from './runtime/planning/service.mjs';
import {createAuthService} from './runtime/planning/auth/service.mjs';
import {commitActivity,captureActivity,notificationRequest} from './account-notifications.mjs';
import {createEventNotifications} from './event-notifications.mjs';
import {runCoordinationTick} from './date-coordination-tick.mjs';
const NOW='2026-09-10T12:00:00.000Z',origin='https://ely0030.xyz';
class Memory{data=emptyState();etag=1;async getWithMetadata(){return {data:structuredClone(this.data),etag:String(this.etag)}}async setJSON(k,d,{onlyIfMatch}){if(this.fail)throw Error('failed commit');if(this.conflict){this.conflict=false;this.etag++;return {modified:false}}if(onlyIfMatch!==String(this.etag))return {modified:false};this.data=structuredClone(d);this.etag++;return {modified:true}}}
async function fixture(){let at=NOW;const store=new Memory(),c=openState(store.data),tokens={},messages=[];for(const [i,id] of ['one','two','three'].entries())c.authStore.db.prepare('INSERT INTO participants(id,email,created_at,onboarded,name,avatar_id) VALUES(?,?,?,?,?,?)').run(id,'captured.'+id+'@gmail.com',NOW,1,id,i);
 const auth=createAuthService({store:c.authStore,avatars:[],now:()=>at});for(const id of ['one','two','three'])tokens[id]=auth.issueSession(id,'code').token;
 const svc=createPlanningService({store:c.plans,adminToken:'admin',now:()=>at});await svc.seed({id:'group',title:'Film',window:{start:'2026-09-01',end:'2026-09-30'},options:['a','b','c','d','e','f'].map(id=>({id,title:id.toUpperCase()}))});await svc.setRound('group','admin','initial-shortlist-01',{shortlist:['a','b','c']});store.data=c.export();c.close();
 const mail=createEventNotifications({store,enabled:true,activatedAt:'2026-09-10T11:00:00Z',allowAnyRecipient:true,now:()=>at,send:async m=>{messages.push(m);return {providerId:'captured'}}});
 const api=createApi({store,blobs:{},adminToken:'admin',origin,now:()=>at,queueEvents:mail.queue});let serial=0;
 async function req(path,method='GET',body,who='one',key){const response=await api(new Request(origin+'/filmmaand/api/'+path,{method,headers:{origin,authorization:'Bearer '+(who==='admin'?'admin':tokens[who]),'idempotency-key':key||('notification-key-'+(++serial)).padEnd(24,'x'),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}));return {status:response.status,body:await response.json()};}
 const feed=who=>req('notifications','GET',null,who),change=async(action,extra={})=>{const r=(await req('plans/group/vote')).body.round;return req('plans/group/round','POST',{action,expectedRoundId:r.id,expectedRevision:r.revision,...extra},'admin');};
 return {store,req,feed,change,mail,messages,setAt:value=>at=value};
}
test('real API: committed suggestion/like only, private recipients, CAS retry and replay, grouped version ACK, preference and no public leak',async()=>{
 const f=await fixture();const before=structuredClone(f.store.data);assert.deepEqual((await f.feed('one')).body.items,[]);assert.equal(f.store.data.accountNotifications,undefined);
 const key='notification-suggestion-01',body={title:'A new film'};f.store.conflict=true;const suggested=await f.req('plans/group/suggestions','POST',body,'one',key);assert.equal(suggested.status,200);const id=suggested.body.option.id;
 assert.equal((await f.feed('one')).body.items.length,0);assert.equal((await f.feed('two')).body.items.filter(i=>i.type==='film-suggested').length,1);await f.req('plans/group/suggestions','POST',body,'one',key);assert.equal((await f.feed('two')).body.items.filter(i=>i.type==='film-suggested').length,1);
 const bad=await f.req('plans/group/response','PUT',{expectedRevision:99,choices:[id],dates:[]},'two');assert.equal(bad.status,409);assert.equal((await f.feed('one')).body.items.length,0);
 assert.equal((await f.req('plans/group/response','PUT',{expectedRevision:0,choices:[id],dates:[]},'two')).status,200);const liked=(await f.feed('one')).body.items.find(i=>i.type==='suggestion-liked');assert.ok(liked);assert.deepEqual(liked.actor,{name:'two',avatarId:1});assert.ok(!(await f.feed('three')).body.items.some(i=>i.type==='suggestion-liked'));
 await f.req('notifications/read','POST',{items:[{id:liked.id,updatedAt:liked.updatedAt}]},'two');assert.equal((await f.feed('one')).body.items.find(i=>i.id===liked.id).readAt,null);
 f.setAt('2026-09-10T12:00:02.000Z');await f.req('plans/group/response','PUT',{expectedRevision:0,choices:[id],dates:[]},'three');await f.req('notifications/read','POST',{items:[liked]},'one');const latest=(await f.feed('one')).body.items.find(i=>i.id===liked.id);assert.equal(latest.count,2);assert.match(latest.text,/2 keer een hartje/);assert.equal(latest.readAt,null);await f.req('notifications/read','POST',{items:[latest]},'one');assert.ok((await f.feed('one')).body.items.find(i=>i.id===liked.id).readAt);
 assert.equal((await f.req('notifications/read','POST',{allThrough:'2099-01-01T00:00:00Z'})).status,400);assert.equal((await f.req('notifications/preferences','PUT',{importantActivityEmail:false})).status,200);assert.equal((await f.feed('one')).body.preferences.importantActivityEmail,false);
 const wire=JSON.stringify((await f.req('plans/group')).body);assert.doesNotMatch(wire,/accountNotifications|mailIntents|captured.one/);assert.equal(before.plans.group.data.options.length,6);
});
test('real vote transitions retain truthful ties, conclude + open histories, scheduler baseline and captured outbox exactly once',async()=>{
 const f=await fixture();await runCoordinationTick({store:f.store,now:()=>NOW,queueEvents:f.mail.queue});assert.equal(f.messages.length,0);assert.equal((await f.feed('one')).body.items.length,0);
 await f.req('plans/group/vote','PUT',{expectedRevision:0,final:'a'},'one');await f.req('plans/group/vote','PUT',{expectedRevision:0,final:'b'},'two');let feed=(await f.feed('three')).body;assert.match(feed.items.find(i=>i.type==='vote-leader').text,/Gelijke stand/);assert.equal(feed.items.filter(i=>i.type==='vote-leader').length,1);
 await f.req('plans/group/response','PUT',{expectedRevision:0,choices:['d','e','f'],rankingOrder:['d','e','f'],dates:[]},'three');assert.ok((await f.feed('one')).body.items.some(i=>i.type==='leaderboard-entry'));assert.match((await f.feed('one')).body.items.find(i=>i.type==='next-leader').text,/D staat bovenaan/);
 await f.change('deadline',{closesAt:'2026-09-10T12:01:00Z'});f.setAt('2026-09-10T12:02:00.000Z');await runCoordinationTick({store:f.store,now:()=> '2026-09-10T12:02:00.000Z',queueEvents:f.mail.queue});feed=(await f.feed('three')).body;assert.match(feed.items.find(i=>i.type==='round-concluded').text,/gelijke stand/);await Promise.all([f.mail.drain(),f.mail.drain()]);assert.equal(f.messages.length,3);assert.match(f.messages[0].text,/gelijke stand/);await f.mail.drain();assert.equal(f.messages.length,3);
 assert.equal((await f.change('resolve',{choice:'a'})).status,200);assert.match((await f.feed('three')).body.items.find(i=>i.type==='round-concluded').text,/afgerond: A/);
 const next=(await f.req('plans/group')).body.nextRound;assert.equal((await f.change('open',{selectionSnapshot:next.snapshot,shortlist:next.shortlist,scheduledDate:'2026-09-14',closesAt:'2026-09-11T12:00:00Z'})).status,200);assert.ok((await f.feed('one')).body.items.some(i=>i.type==='round-opened'));await f.mail.drain();assert.equal(f.messages.filter(m=>/Kies de volgende film/.test(m.subject)).length,3);
});
test('retention and read fence are bounded, missing anonymous session is refused',async()=>{
 const f=await fixture();const response=await f.req('notifications','GET',null,'missing');assert.equal(response.status,401);
 const c=openState(f.store.data);c.state.accountNotifications={accounts:{one:{items:Array.from({length:110},(_,i)=>({id:String(i),updatedAt:NOW,createdAt:NOW,readAt:null})),importantActivityEmail:true}},baselines:{},mailIntents:{}};commitActivity(c,captureActivity(c,NOW),NOW);assert.equal(c.state.accountNotifications.accounts.one.items.length,100);const args={method:'GET',url:new URL(origin+'/?limit=20'),at:NOW};const page=notificationRequest(c,'one',args);assert.equal(page.items.length,20);assert.ok(page.nextCursor);assert.equal(notificationRequest(c,'one',{...args,method:'POST',part:'read',body:{allThrough:NOW}}).unreadCount,0);c.close();
});
test('failed outer commit cannot deliver history or important mail',async()=>{const f=await fixture();f.store.fail=true;assert.equal((await f.req('plans/group/suggestions','POST',{title:'Failure'})).status,503);f.store.fail=false;assert.equal((await f.feed('two')).body.items.length,0);await f.mail.drain();assert.equal(f.messages.length,0);});
test('important preference cancels pending mail, result/date confirmation coalesce even when date log follows next tick',async()=>{
 const f=await fixture();await f.req('plans/group/round-date','POST',{date:'2026-09-14'},'admin');await f.req('plans/group/vote','PUT',{expectedRevision:0,final:'a'});await f.change('close');assert.equal((await f.change('resolve',{choice:'a',programme:true})).status,200);await f.req('notifications/preferences','PUT',{importantActivityEmail:false},'two');await f.mail.drain();assert.equal(f.messages.length,2);assert.ok(f.messages.every(m=>/afgerond: A/.test(m.text)&&/14 september/.test(m.text)));
 const current=f.store.data.plans.group.data,night=current.programme[0];current.coordinationEvents||=[];current.coordinationEvents.push({id:'later-date-log',type:'date-confirmed',planId:'group',eventId:night.id,occurredAt:'2026-09-10T12:00:01.000Z',scheduledDate:'2026-09-14',title:'A',choices:['a']});f.setAt('2026-09-10T12:00:02.000Z');await transact(f.store,c=>f.mail.queue(c));await f.mail.drain();
 // The recipient who disabled important activity retains separate existing date notifications.
 assert.equal(f.messages.length,3);assert.equal(f.messages.at(-1).to,'captured.two@gmail.com');
});
test('same-transaction confirmation includes actual result without duplicate unresolved mail',async()=>{
 const f=await fixture();await f.req('plans/group/round-date','POST',{date:'2026-09-14'},'admin');await f.req('plans/group/vote','PUT',{expectedRevision:0,final:'a'});await f.change('close');
 // Prepare canonical event exactly as resolve will create it; disable queuing while building the state for one batch.
 const c=openState(f.store.data),before=captureActivity(c,NOW),svc=createPlanningService({store:c.plans,adminToken:'admin',now:()=>NOW});const r=(await svc.get('group')).round;await svc.setRound('group','admin','resolve-coalesce-key',{action:'resolve',expectedRoundId:r.id,expectedRevision:r.revision,choice:'a',programme:true});const p=c.state.plans.group.data,night=p.programme[0];p.coordinationEvents=[{id:'same-date-log',type:'date-confirmed',planId:'group',eventId:night.id,occurredAt:NOW,scheduledDate:'2026-09-14',title:'A',choices:['a']}];commitActivity(c,before,NOW);f.mail.queue(c);f.store.data=c.export();c.close();await f.mail.drain();assert.equal(f.messages.length,3);assert.ok(f.messages.every(m=>/De datum staat vast/.test(m.text)&&/afgerond: A/.test(m.text)&&/afgerond: A/.test(m.html)));
});
test('claimed canonical suggester keeps credit and self likes stay excluded',async()=>{
 const f=await fixture(),c=openState(f.store.data),svc=createPlanningService({store:c.plans,adminToken:'admin',now:()=>NOW}),anon='z'.repeat(43);const {option}=await svc.suggest('group',anon,'legacy-suggestion-01',{title:'Claimed film'});const {createActorTransfer}=await import('./runtime/planning/auth/transfer.mjs');const {createHash}=await import('node:crypto');await createActorTransfer({store:c.plans})('group',createHash('sha256').update(anon).digest('hex'),'p_one','legacy-claim-key-01');f.store.data=c.export();c.close();await f.req('plans/group/response','PUT',{expectedRevision:0,choices:[option.id],dates:[]},'one');assert.ok(!(await f.feed('one')).body.items.some(i=>i.type==='suggestion-liked'));await f.req('plans/group/response','PUT',{expectedRevision:0,choices:[option.id],dates:[]},'two');assert.ok((await f.feed('one')).body.items.some(i=>i.type==='suggestion-liked'));
});

test('grouped next-shortlist entrant updates its direct link with latest text',async()=>{
 const f=await fixture();await f.req('plans/group/response','PUT',{expectedRevision:0,choices:['d'],dates:[]},'one');const first=(await f.feed('two')).body.items.find(i=>i.type==='leaderboard-entry');assert.equal(first.href,'/filmmaand/films/?film=d');f.setAt('2026-09-10T12:00:03.000Z');await f.req('plans/group/response','PUT',{expectedRevision:1,choices:['e'],dates:[]},'one');const latest=(await f.feed('two')).body.items.find(i=>i.type==='leaderboard-entry');assert.equal(latest.id,first.id);assert.equal(latest.href,'/filmmaand/films/?film=e');assert.match(latest.text,/E staat nu/);
});
