import test from 'node:test';import assert from 'node:assert/strict';
import sharp from 'sharp';import {readFile} from 'node:fs/promises';import {createApi} from './api.mjs';import {emptyState,openState} from './state.mjs';import {createMail} from './mail.mjs';import {createPlanningService} from './runtime/planning/service.mjs';
class Memory{constructor(){const c=openState(emptyState());this.data=c.export();c.close();this.etag=1}async getWithMetadata(){return {data:structuredClone(this.data),etag:String(this.etag)}}async setJSON(k,data,{onlyIfMatch}){if(String(this.etag)!==onlyIfMatch)return {modified:false};this.data=structuredClone(data);this.etag++;return {modified:true}}}
async function fixture(){const images=new Map();const blobs={async set(k,v){images.set(k,Buffer.from(v));return {modified:true}},async get(k){return images.get(k)||null},async getMetadata(k){return images.has(k)?{}:null}};const store=new Memory(),c=openState(store.data),seed=JSON.parse(await readFile(new URL('./runtime/planning/seed.json',import.meta.url)));await createPlanningService({store:c.plans,adminToken:'admin'}).seed(seed);store.data=c.export();c.close();let sent=[];const mail=createMail({store,enabled:true,apiKey:'synthetic-key',from:'test@example.test',allowedRecipients:['person@example.test'],fetcher:async(url,options)=>{sent.push(options);return new Response('{}',{status:200})}});const api=createApi({store,blobs,adminToken:'admin',queueMail:mail.queue,deliverMail:mail.deliver});const req=async(path,method='GET',body,headers={})=>{const response=await api(new Request('https://ely0030.xyz/filmmaand/api/'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}),{ip:'test-ip'});return {status:response.status,headers:response.headers,body:await response.json()}};return {store,req,sent,seed,mail,api,images}}
test('HTTP login is durable before delivery; profile cookie scope and public projection remain correct',async()=>{const f=await fixture();const code=await f.req('auth/code','POST',{email:'person@example.test'});assert.equal(code.status,200);assert.equal(f.sent.length,1);assert.equal(Object.keys(f.store.data.outbox).length,0);const payload=JSON.parse(f.sent[0].body),digits=payload.text.match(/\b\d{6}\b/)[0];const login=await f.req('auth/verify','POST',{challengeId:code.body.challengeId,code:digits});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.match(cookie,/Path=\/filmmaand\/; HttpOnly; SameSite=Lax/);assert.match(cookie,/Secure/);assert.equal(f.store.data.auth.sessions.length,1);const headers={Cookie:cookie.split(';')[0],Origin:'https://ely0030.xyz','Idempotency-Key':'profile-proof-000001'};const profile=await f.req('auth/profile','PUT',{expectedRevision:0,name:'Synthetic',animal:'otter',avatarId:4},headers);assert.equal(profile.status,200);const own=await f.req('auth/session','GET',null,headers);assert.equal(own.body.participant.onboarded,true);const publicPlan=await f.req('plans/'+f.seed.id);assert.equal(publicPlan.status,200);const wire=JSON.stringify(publicPlan.body);assert.equal(wire.includes('person@example.test'),false);assert.equal(wire.includes('code_hash'),false);assert.equal(wire.includes('token_hash'),false);const blocked=await f.req('auth/profile','PUT',{expectedRevision:1,name:'Hacker',animal:'otter',avatarId:4},{Cookie:headers.Cookie,'Idempotency-Key':'profile-proof-000002'});assert.equal(blocked.status,403)});
test('mail lost acknowledgement retries the same durable message and provider key; expired outbox is never delivered',async()=>{const store=new Memory();let attempts=[];let fail=true;const mail=createMail({store,enabled:true,apiKey:'synthetic',from:'sender@example.test',allowedRecipients:['person@example.test'],fetcher:async(u,o)=>{attempts.push(o);if(fail)throw Error('lost acknowledgement');return new Response('{}')}});const api=createApi({store,blobs:{},queueMail:mail.queue,deliverMail:mail.deliver});const response=await api(new Request('https://ely0030.xyz/filmmaand/api/auth/code',{method:'POST',body:JSON.stringify({email:'person@example.test'})}));assert.equal(response.status,503);const id=Object.keys(store.data.outbox)[0];assert.ok(id);fail=false;await mail.deliver(id);assert.equal(attempts.length,2);assert.equal(attempts[0].headers['Idempotency-Key'],attempts[1].headers['Idempotency-Key']);assert.equal(attempts[0].body,attempts[1].body);assert.equal(Object.keys(store.data.outbox).length,0);store.data.outbox[id]={to:'person@example.test',expiresAt:'2000-01-01T00:00:00Z'};await mail.deliver(id);assert.equal(attempts.length,2);assert.equal(Object.keys(store.data.outbox).length,0)});
test('anonymous availability claim and lost vote response survive session replacement with exact receipt replay',async()=>{
 const f=await fixture(),anon='a'.repeat(43),anonHeaders={Authorization:'Bearer '+anon,'Idempotency-Key':'anonymous-save-0001'};
 const draft={expectedRevision:0,dates:['2026-09-12'],choices:['blade','matrix'],rankingOrder:['matrix','blade']};
 const legacy=openState(f.store.data);await createPlanningService({store:legacy.plans}).submit(f.seed.id,anon,anonHeaders['Idempotency-Key'],draft);f.store.data=legacy.export();legacy.close();
 const code=await f.req('auth/code','POST',{email:'person@example.test'});const digits=JSON.parse(f.sent[0].body).text.match(/\b\d{6}\b/)[0];
 const login=await f.req('auth/verify','POST',{challengeId:code.body.challengeId,code:digits});
 const headers={Cookie:login.headers.get('set-cookie').split(';')[0],Origin:'https://ely0030.xyz','Idempotency-Key':'profile-proof-claim1'};
 assert.equal((await f.req('auth/profile','PUT',{expectedRevision:0,name:'Synthetic',animal:'otter',avatarId:4},headers)).status,200);
 const claim=await f.req('auth/claim','POST',{planId:f.seed.id,anonymousBearer:anon},{...headers,'Idempotency-Key':'claim-proof-000001'});assert.equal(claim.status,200);
 const own=await f.req('plans/'+f.seed.id+'/response','GET',null,headers);assert.deepEqual(own.body.response.choices,draft.choices);assert.deepEqual(own.body.response.rankingOrder,draft.rankingOrder);
 const view=await f.req('plans/'+f.seed.id+'/vote','GET',null,headers);const voteBody={expectedRevision:0,final:view.body.round.shortlist[0]},voteHeaders={...headers,'Idempotency-Key':'lost-vote-proof-001'};
 const committed=await f.req('plans/'+f.seed.id+'/vote','PUT',voteBody,voteHeaders);assert.equal(committed.status,200);
 // Drop the successful response at the transport boundary, then expire the persisted session.
 f.store.data.auth.sessions.forEach(s=>{s.expires_at='2000-01-01T00:00:00Z'});
 assert.equal((await f.req('plans/'+f.seed.id+'/vote','PUT',voteBody,voteHeaders)).status,401);
 // Controlled test clock/rate reset permits immediate second login without weakening production limits.
 f.store.data.auth.rate_limits=[];
 const code2=await f.req('auth/code','POST',{email:'person@example.test'});const digit2=JSON.parse(f.sent.at(-1).body).text.match(/\b\d{6}\b/)[0];
 const login2=await f.req('auth/verify','POST',{challengeId:code2.body.challengeId,code:digit2});assert.equal(login2.status,200);
 const retry=await f.req('plans/'+f.seed.id+'/vote','PUT',voteBody,{...voteHeaders,Cookie:login2.headers.get('set-cookie').split(';')[0]});assert.equal(retry.status,200);assert.deepEqual(retry.body,committed.body);
 const p=f.store.data.plans[f.seed.id].data;assert.equal(Object.values(p.votes).length,1);assert.equal(Object.values(p.votes)[0].revision,1);
});
test('native upload normalizes raster and serves its saved suggestion URL through the deployment prefix',async()=>{const f=await fixture(),accountHeaders=await onboard(f),png=await sharp({create:{width:1400,height:700,channels:3,background:'red'}}).png().toBuffer();const upload=await f.req('plans/'+f.seed.id+'/images','POST',{data:'data:image/png;base64,'+png.toString('base64')},accountHeaders);assert.equal(upload.status,200);assert.match(upload.body.image.url,/^\/filmmaand\/api\/images\/[a-f0-9]{64}\.webp$/);const suggestion=await f.req('plans/'+f.seed.id+'/suggestions','POST',{title:'Synthetic image theme',imageId:upload.body.image.id},{...accountHeaders,'Idempotency-Key':'image-suggest-proof1'});assert.equal(suggestion.status,200);assert.equal(suggestion.body.option.image.url,upload.body.image.url);const response=await f.api(new Request('https://ely0030.xyz'+suggestion.body.option.image.url));assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/webp');const bytes=Buffer.from(await response.arrayBuffer()),meta=await sharp(bytes).metadata();assert.equal(meta.width,1200);assert.equal(meta.height,600);assert.equal(meta.exif,undefined);const publicPlan=await f.req('plans/'+f.seed.id);assert.equal(publicPlan.body.options.find(o=>o.id===suggestion.body.option.id).image.url,upload.body.image.url)});

async function onboard(f){const challenge=await f.req('auth/code','POST',{email:'person@example.test'});assert.equal(challenge.status,200);const code=JSON.parse(f.sent.at(-1).body).text.match(/\b\d{6}\b/)[0];const login=await f.req('auth/verify','POST',{challengeId:challenge.body.challengeId,code});assert.equal(login.status,200);const headers={Cookie:login.headers.get('set-cookie').split(';')[0],Origin:'https://ely0030.xyz','Idempotency-Key':'account-profile-00001'};assert.equal((await f.req('auth/profile','PUT',{expectedRevision:0,name:'Test account',animal:'otter',avatarId:4},headers)).status,200);return headers}
test('participant writes require an account before side effects, while public reads and organizer actions remain available',async()=>{
 const f=await fixture(),before=structuredClone(f.store.data);
 for(const [method,part] of [['PUT','response'],['PUT','vote'],['PUT','proposals'],['POST','suggestions'],['POST','images'],['PUT','profile']]){
  for(const headers of [{},{Authorization:'Bearer '+'a'.repeat(43)}]){const r=await f.req('plans/'+f.seed.id+'/'+part,method,{},headers);assert.equal(r.status,401,part);assert.equal(r.body.error.code,'session_invalid')}
 }
 assert.deepEqual(f.store.data,before);assert.equal(f.images.size,0);
 assert.equal((await f.req('plans/'+f.seed.id)).status,200);
 const admin=await f.req('plans/'+f.seed.id+'/round-date','POST',{date:'2026-09-09'},{Authorization:'Bearer admin','Idempotency-Key':'organizer-date-00001'});assert.equal(admin.status,200);assert.equal(admin.body.round.scheduledDate,'2026-09-09');
});
test('verified but incomplete account receives onboarding_required until profile is saved',async()=>{
 const f=await fixture(),ch=await f.req('auth/code','POST',{email:'person@example.test'}),code=JSON.parse(f.sent.at(-1).body).text.match(/\b\d{6}\b/)[0];const login=await f.req('auth/verify','POST',{challengeId:ch.body.challengeId,code});
 const headers={Cookie:login.headers.get('set-cookie').split(';')[0],Origin:'https://ely0030.xyz','Idempotency-Key':'availability-000001'},draft={expectedRevision:0,dates:['2026-09-12'],choices:['blade']};const before=structuredClone(f.store.data.plans);
 const blocked=await f.req('plans/'+f.seed.id+'/response','PUT',draft,headers);assert.equal(blocked.status,409);assert.equal(blocked.body.error.code,'onboarding_required');assert.deepEqual(f.store.data.plans,before);
 assert.equal((await f.req('auth/profile','PUT',{expectedRevision:0,name:'Test account',animal:'otter',avatarId:4},{...headers,'Idempotency-Key':'profile-complete-0001'})).status,200);
 const saved=await f.req('plans/'+f.seed.id+'/response','PUT',draft,headers);assert.equal(saved.status,200);assert.deepEqual(saved.body.response.dates,draft.dates);
});
