import test from 'node:test';import assert from 'node:assert/strict';
import {openAvailabilityPoll,writeAvailability,finalizePoll,rankAvailability,changeDate,resolveChanges,tickCoordination,coordinationView} from './runtime/planning/date-coordination.mjs';
const now='2026-09-10T10:00:00Z',closed='2026-09-11T11:00:00Z',eligible=a=>['p_a','p_b','p_c'].includes(a);
const plan=()=>({id:'qa',version:1,window:{start:'2026-09-01',end:'2026-09-30'},options:[],responses:{},programme:[],receipts:{}});
function poll(p){openAvailabilityPoll(p,{action:'open',mode:'availability',window:{start:'2026-09-12',end:'2026-09-14'},choices:[],closesAt:'2026-09-11T10:00:00Z'},{id:'poll-qa',now});}
test('availability, favourites, chronological tie, unknown and legacy preservation',()=>{const p=plan();p.datePoll={id:'old',status:'closed',votes:{p_a:{date:'2026-09-12'}}};const old=structuredClone(p.datePoll);poll(p);assert.deepEqual(p.datePollHistory,[old]);writeAvailability(p,'p_a',{pollId:'poll-qa',revision:0,availability:{'2026-09-12':true,'2026-09-13':true},favourite:'2026-09-13'},now);writeAvailability(p,'p_b',{pollId:'poll-qa',revision:0,availability:{'2026-09-12':true,'2026-09-13':true},favourite:null},now);assert.equal(rankAvailability(p.datePoll)[0].date,'2026-09-13');assert.equal(rankAvailability(p.datePoll).find(d=>d.date==='2026-09-14').unavailable,0);p.datePoll.votes.p_a.favourite=null;assert.equal(rankAvailability(p.datePoll)[0].date,'2026-09-12');assert.throws(()=>writeAvailability(p,'p_c',{revision:0,availability:{},favourite:'2026-09-12'},now));});
test('deadline commits once, zero positive needs organizer, no legacy auto-finalization',()=>{const p=plan();poll(p);assert.equal(finalizePoll(p,now),false);writeAvailability(p,'p_a',{revision:0,availability:{'2026-09-13':true},favourite:null},now);assert.equal(finalizePoll(p,closed,eligible),true);const exact=structuredClone(p);assert.equal(finalizePoll(p,closed,eligible),false);assert.deepEqual(p,exact);assert.equal(p.programme[0].selection,'pending');assert.equal(p.programme[0].scheduledDate,'2026-09-13');assert.deepEqual(p.responses,{});assert.equal(p.coordinationEvents.length,1);const z=plan();poll(z);finalizePoll(z,closed);assert.equal(z.datePoll.status,'needs-organizer');assert.deepEqual(z.programme,[]);const legacy=plan();legacy.datePoll={status:'open',votes:{p_a:{date:'2026-09-12'}}};assert.equal(finalizePoll(legacy,closed),false);});
function moveFixture(){const p=plan();p.programme=[{id:'night',scheduledDate:'2026-09-12',selection:'pending',choices:[]}];p.responses={p_a:{dates:['2026-09-12']},p_b:{dates:['2026-09-12']}};changeDate(p,'p_a',{action:'propose',eventId:'night',eventVersion:0,proposedDate:'2026-09-14'},{id:'proposal',now,eligible});return p;}
const consent=(p,a,agree,revision=0)=>changeDate(p,a,{action:'consent',eventId:'night',eventVersion:0,proposalId:'proposal',revision,agree},{id:'unused',now,eligible});
test('current attendees must consent, refusal blocks, new joiner required and cancellation no longer blocks',()=>{const p=moveFixture();consent(p,'p_a',true);p.responses.p_c={dates:['2026-09-12']};consent(p,'p_b',true);assert.equal(p.programme[0].scheduledDate,'2026-09-12');consent(p,'p_c',false);assert.equal(p.dateChanges[0].status,'pending');p.responses.p_c.dates=[];const before=structuredClone(p.responses);resolveChanges(p,now,eligible);assert.equal(p.programme[0].scheduledDate,'2026-09-14');assert.deepEqual(p.responses,before);assert.throws(()=>consent(p,'p_c',true,1),e=>e.code==='event_changed');const view=coordinationView(p,'p_a',()=>({name:'QA'}));assert.ok(!JSON.stringify(view).includes('p_b'));});
test('zero attendees cannot auto-move; explicit organizer override, cancellation and version guards',()=>{const p=moveFixture();p.responses={};resolveChanges(p,now,eligible);assert.equal(p.dateChanges[0].status,'pending');assert.throws(()=>changeDate(p,'p_a',{action:'override',eventId:'night',eventVersion:0,proposalId:'proposal'},{now,eligible}));changeDate(p,'admin',{action:'override',eventId:'night',eventVersion:0,proposalId:'proposal'},{now,eligible,admin:true});assert.equal(p.programme[0].scheduledDate,'2026-09-14');assert.equal(p.dateChanges[0].override,true);const c=moveFixture();changeDate(c,'p_a',{action:'cancel',eventId:'night',eventVersion:0,proposalId:'proposal'},{now,eligible});assert.equal(c.dateChanges[0].status,'cancelled');assert.equal(c.programme[0].scheduledDate,'2026-09-12');});
test('manual time labels stay manual; reminder off until explicitly configured and only once',()=>{const p=moveFixture();changeDate(p,'admin',{action:'times',eventId:'night',eventVersion:0,timing:{arrival:'19:00',screening:'19:30',end:''}},{now,eligible,admin:true});assert.equal(p.programme[0].startsAt,undefined);assert.equal(p.programme[0].timing.end,'');assert.equal(p.programme[0].reminderMinutes,undefined);p.programme[0].startsAt='2026-09-12T17:30:00Z';p.programme[0].reminderMinutes=60;tickCoordination(p,'2026-09-12T17:00:00Z',eligible);tickCoordination(p,'2026-09-12T17:01:00Z',eligible);assert.equal(p.coordinationEvents.filter(n=>n.type==='reminder').length,1);});
test('pending move can resolve beyond original date, but never after proposed date',()=>{const p=moveFixture();changeDate(p,'admin',{action:'override',eventId:'night',eventVersion:0,proposalId:'proposal'},{now:'2026-09-13T10:00:00Z',eligible,admin:true});assert.equal(p.programme[0].scheduledDate,'2026-09-14');const stale=moveFixture();resolveChanges(stale,'2026-09-15T10:00:00Z',eligible);assert.equal(stale.dateChanges[0].status,'stale');assert.equal(stale.programme[0].scheduledDate,'2026-09-12');});
