import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,openState,transact} from './state.mjs';
import {createEventNotifications,queueCoordinationEvents,renderEventNotification} from './event-notifications.mjs';
const NOW='2026-09-10T12:00:00.000Z',ACTIVATED='2026-09-10T10:00:00.000Z';
const notice=(extra={})=>({id:'decision-1',type:'date-confirmed',planId:'group',eventId:'night-1',eventVersion:2,occurredAt:NOW,scheduledDate:'2026-09-18',title:'Filmavond',timing:{},choices:[],...extra});
class Memory{
 constructor(){this.data=emptyState();this.data.auth.participants=[{id:'one',email:'captured.one@gmail.com',created_at:NOW},{id:'two',email:'captured.two@gmail.com',created_at:NOW}];this.data.plans.group={version:1,data:{id:'group',options:[],programme:[{id:'night-1',scheduledDate:'2026-09-18',coordinationRevision:2}],coordinationEvents:[notice()]}};this.etag=1;}
 async getWithMetadata(){return {data:structuredClone(this.data),etag:String(this.etag)}}
 async setJSON(key,data,{onlyIfMatch}){if(this.failWrites)throw Error('synthetic failed commit');if(this.conflict){this.conflict=false;this.etag++;return {modified:false}}if(onlyIfMatch!==String(this.etag))return {modified:false};this.data=structuredClone(data);this.etag++;return {modified:true}}
}
function fixture(extra={}){const store=new Memory(),messages=[],options={store,enabled:true,activatedAt:ACTIVATED,allowAnyRecipient:true,now:()=>NOW,send:async(m)=>{messages.push(m);return {providerId:'<captured@provider.test>'}},...extra};const mail=createEventNotifications(options);return {store,messages,mail,options,queue:()=>transact(store,c=>mail.queue(c))};}
test('queue happens inside state CAS and delivery only sees committed notices',async()=>{const f=fixture();const c=openState(f.store.data);f.mail.queue(c);await f.mail.drain();assert.equal(f.messages.length,0);c.close();f.store.conflict=true;await f.queue();assert.equal(f.messages.length,0);await f.mail.drain();assert.equal(f.messages.length,2);assert.equal(f.store.data.eventNotifications.receipts.length,2);await f.queue();await f.mail.drain();assert.equal(f.messages.length,2);});
test('failed state commit cannot emit messages',async()=>{const f=fixture();f.store.failWrites=true;await assert.rejects(f.queue());f.store.failWrites=false;await f.mail.drain();assert.equal(f.messages.length,0);});
test('concurrent drains and retries deliver once per event/member',async()=>{const f=fixture();await f.queue();await Promise.all([f.mail.drain(),f.mail.drain(),f.mail.drain()]);assert.equal(f.messages.length,2);assert.equal(new Set(f.messages.map(x=>x.to)).size,2);});
test('disabled, missing activation and preactivation logs never create a backlog',async()=>{for(const config of [{enabled:false},{activatedAt:null},{activatedAt:'2026-09-10T13:00:00Z'}]){const f=fixture(config);await f.queue();await f.mail.drain();assert.equal(f.messages.length,0);assert.equal(f.store.data.eventNotifications,undefined);}const f=fixture();f.store.data.plans.group.data.coordinationEvents=[notice({occurredAt:'2026-09-09T23:59:00Z'})];await f.queue();assert.equal(Object.keys(f.store.data.eventNotifications.outbox).length,0);});
test('unverified, opted-out, suppressed, excluded and demo accounts are not eligible',async()=>{const f=fixture();const people=f.store.data.auth.participants;for(const [id,email] of [['unverified','captured.three@gmail.com'],['optout','captured.four@gmail.com'],['suppressed','captured.five@gmail.com'],['excluded','captured.six@gmail.com'],['demo','demo@example.test']])people.push({id,email,created_at:NOW});f.store.data.auth.email_ownership=[{participant_id:'unverified',verified_at:null}];f.store.data.eventNotificationPreferences={optout:{email:false}};f.store.data.eventNotificationSuppressions={'captured.five@gmail.com':{reason:'bounce'}};f.store.data.eventNotificationExcludedParticipantIds=['excluded'];await f.queue();await f.mail.drain();assert.deepEqual(f.messages.map(m=>m.to).sort(),['captured.one@gmail.com','captured.two@gmail.com']);});
test('recipient membership, address and opt-out are rechecked immediately before claim',async()=>{for(const mutate of [s=>s.auth.participants.splice(0,1),s=>s.auth.participants[0].email='changed@gmail.com',s=>s.eventNotificationPreferences={one:false},s=>s.eventNotificationSuppressions={'captured.one@gmail.com':true}]){const f=fixture();await f.queue();mutate(f.store.data);await f.mail.drain();assert.deepEqual(f.messages.map(m=>m.to),['captured.two@gmail.com']);}});
test('registration allow-list is enforced for notifications',async()=>{const f=fixture({allowAnyRecipient:false,allowedRecipients:['captured.two@gmail.com']});await f.queue();await f.mail.drain();assert.deepEqual(f.messages.map(m=>m.to),['captured.two@gmail.com']);});
test('timeout and lost acknowledgement cannot automatically duplicate send',async()=>{const f=fixture({send:async()=>{throw Error('synthetic timeout')}});await f.queue();let calls=0;const mail=createEventNotifications({...f.options,send:async()=>{calls++;throw Error('synthetic timeout')}});await mail.drain();await mail.drain();assert.equal(calls,2);assert.equal(Object.values(f.store.data.eventNotifications.outbox).every(m=>m.status==='attempted'),true);});
test('lost acceptance persistence keeps committed attempt fence',async()=>{const f=fixture();await f.queue();let calls=0;const mail=createEventNotifications({...f.options,send:async()=>{calls++;f.store.failWrites=true;return {providerId:null}}});await assert.rejects(mail.deliver(Object.keys(f.store.data.eventNotifications.outbox)[0]));f.store.failWrites=false;await mail.deliver(Object.keys(f.store.data.eventNotifications.outbox)[0]);assert.equal(calls,1);});
test('newer date decision cancels obsolete queued notices, including same-clock versions',async()=>{const f=fixture();await f.queue();f.store.data.plans.group.data.coordinationEvents.push(notice({id:'decision-2',type:'date-changed',eventVersion:3,previousDate:'2026-09-18',scheduledDate:'2026-09-19'}));await f.mail.drain();assert.equal(f.messages.length,0);await f.queue();await f.mail.drain();assert.equal(f.messages.length,2);assert.match(f.messages[0].text,/18 september 2026 vervalt/);assert.match(f.messages[0].text,/19 september 2026/);});
test('confirmation includes arrival and omits unknown start, retaining end, films and escaped titles',()=>{const n=notice({title:'<img src=x onerror=1>',timing:{arrival:'19:15',end:'ongeveer 23:00'},films:['Film & vrienden']});const m=renderEventNotification(n);assert.match(m.text,/Inloop: 19:15/);assert.match(m.html,/Inloop/);assert.match(m.html,/19:15/);assert.match(m.text,/Einde: ongeveer 23:00/);assert.doesNotMatch(m.text,/Film start|Aanvang/);assert.match(m.html,/&lt;img/);assert.doesNotMatch(m.html,/<img src=x/);assert.match(m.text,/Film & vrienden/);assert.match(m.html,/Zie programma/);assert.match(m.text,/\/filmmaand\/programma\//);});
test('proposal distinguishes required consent from other group members and leaves original date',()=>{const n=notice({type:'date-change-proposed',proposedDate:'2026-09-19',requiredActors:['p_one'],proposalId:'proposal-1'});const required=renderEventNotification(n,{participantId:'one'}),other=renderEventNotification(n,{participantId:'two'});assert.match(required.text,/Jouw expliciete akkoord/);assert.doesNotMatch(other.text,/Jouw expliciete akkoord/);assert.match(required.text,/huidige datum blijft staan/);assert.match(required.text,/Reageer op het voorstel/);assert.match(required.text,/niet over je algemene beschikbaarheid/);});
test('reminders are sent only when the scheduler explicitly emits a committed reminder',async()=>{const f=fixture();f.store.data.plans.group.data.coordinationEvents=[];await f.queue();await f.mail.drain();assert.equal(f.messages.length,0);f.store.data.plans.group.data.coordinationEvents.push(notice({id:'reminder-explicit',type:'reminder'}));await f.queue();await f.mail.drain();assert.equal(f.messages.length,2);assert.match(f.messages[0].subject,/Herinnering/);});
test('Mailgun uses existing EU config, sender, disabled tracking and required TLS with captured fetch',async()=>{const calls=[],f=fixture({send:undefined,provider:'mailgun',apiKey:'synthetic-key',domain:'example.org',from:'Alec Filmmaand <login@example.org>',fetcher:async(url,opts)=>{calls.push({url,...opts});return Response.json({id:'<captured@provider.test>'})}});await f.queue();await f.mail.drain();assert.equal(calls.length,2);assert.equal(calls[0].url,'https://api.eu.mailgun.net/v3/example.org/messages');assert.equal(calls[0].body.get('from'),'Alec Filmmaand <login@example.org>');for(const k of ['o:tracking','o:tracking-opens','o:tracking-clicks'])assert.equal(calls[0].body.get(k),'no');assert.equal(calls[0].body.get('o:require-tls'),'yes');});
test('shared mail quota defers notifications without consuming their attempt',async()=>{const f=fixture();f.store.data.mailUsage={'2026-09-10':80};await f.queue();await f.mail.drain();assert.equal(f.messages.length,0);assert.equal(Object.values(f.store.data.eventNotifications.outbox).every(m=>m.status==='pending'),true);});
test('malformed committed dates are ignored without breaking the state transaction',async()=>{const f=fixture();f.store.data.plans.group.data.coordinationEvents=[notice({scheduledDate:'2026-99-99'})];await f.queue();assert.equal(Object.keys(f.store.data.eventNotifications.outbox).length,0);});

test('notifications delayed beyond the event calendar day are discarded',async()=>{const f=fixture();await f.queue();const later=createEventNotifications({...f.options,now:()=> '2026-09-19T12:00:00Z'});await later.drain();assert.equal(f.messages.length,0);assert.equal(Object.keys(f.store.data.eventNotifications.outbox).length,0);});

test('withdrawn, completed, stale or missing proposals never dispatch old agreement requests',async()=>{for(const status of ['cancelled','changed','stale',null]){const f=fixture();const p=f.store.data.plans.group.data;p.coordinationEvents=[notice({type:'date-change-proposed',proposalId:'proposal-1',proposedDate:'2026-09-19',requiredActors:['p_one']})];p.dateChanges=[{id:'proposal-1',eventId:'night-1',status:'pending',requiredActors:['p_one']}];await f.queue();if(status)p.dateChanges[0].status=status;else p.dateChanges=[];/* mutate committed fixture after queue */f.store.data.plans.group.data.dateChanges=p.dateChanges;await f.mail.drain();assert.equal(f.messages.length,0);}});
test('current proposal roster determines recipient consent wording',async()=>{const f=fixture();const p=f.store.data.plans.group.data;p.coordinationEvents=[notice({type:'date-change-proposed',proposalId:'proposal-1',proposedDate:'2026-09-19',requiredActors:['p_one']})];p.dateChanges=[{id:'proposal-1',eventId:'night-1',status:'pending',requiredActors:['p_one'],currentRequiredActors:['p_two']}];await f.queue();await f.mail.drain();assert.doesNotMatch(f.messages.find(m=>m.to==='captured.one@gmail.com').text,/Jouw expliciete akkoord/);assert.match(f.messages.find(m=>m.to==='captured.two@gmail.com').text,/Jouw expliciete akkoord/);});
test('removed Programme event or newer canonical revision cancels queued notice without relying on log',async()=>{for(const remove of [true,false]){const f=fixture();await f.queue();const p=f.store.data.plans.group.data;if(remove)p.programme=[];else p.programme[0].coordinationRevision=3;await f.mail.drain();assert.equal(f.messages.length,0);}});

test('live pending proposal survives its old date while proposed date is still future',async()=>{for(const proposedDate of ['2026-09-18','2026-09-09']){const f=fixture();const p=f.store.data.plans.group.data;p.programme[0].scheduledDate='2026-09-08';p.coordinationEvents=[notice({type:'date-change-proposed',scheduledDate:'2026-09-08',proposedDate,proposalId:'proposal-1'})];p.dateChanges=[{id:'proposal-1',eventId:'night-1',status:'pending',previousDate:'2026-09-08',proposedDate,requiredActors:[]}];await f.queue();await f.mail.drain();assert.equal(f.messages.length,proposedDate==='2026-09-18'?2:0);}});

test('empty current consent roster does not fall back to creation snapshot',async()=>{const f=fixture();const p=f.store.data.plans.group.data;p.coordinationEvents=[notice({type:'date-change-proposed',proposalId:'proposal-1',proposedDate:'2026-09-19',requiredActors:['p_one']})];p.dateChanges=[{id:'proposal-1',eventId:'night-1',status:'pending',requiredActors:['p_one'],currentRequiredActors:[]}];await f.queue();await f.mail.drain();assert.equal(f.messages.length,2);for(const m of f.messages)assert.doesNotMatch(m.text,/Jouw expliciete akkoord/);});

test('confirmation shows three ordered moments with next-day end',()=>{const m=renderEventNotification(notice({title:'Indiana Jones Marathon',timing:{arrival:'18:00',screening:'19:00',end:'01:00 (+1 dag)'},films:['Indiana Jones Marathon']}));for(const part of [m.html,m.text]){assert.match(part,/18:00/);assert.match(part,/19:00/);assert.match(part,/01:00/);assert.match(part,/\+1 dag/);assert.ok(part.indexOf('Inloop')<part.indexOf('Aanvang'));assert.ok(part.indexOf('Aanvang')<part.indexOf('Einde'))}assert.equal((m.html.match(/<a href=/g)||[]).length,1)});
