import test from 'node:test';import assert from 'node:assert/strict';
import {resolvedEventTiming} from './runtime/planning/event-timing.mjs';
import {createPlanningService} from './runtime/planning/service.mjs';
class Memory{row=null;etag=0;async read(){return this.row?{data:structuredClone(this.row),etag:String(this.etag)}:null}async compareAndSwap(id,etag,value){if(etag!==(this.row?String(this.etag):null))return false;this.row=structuredClone(value);this.etag++;return true}}
async function fixture(){const store=new Memory(),service=createPlanningService({store,adminToken:'qa-admin',now:()=> '2026-09-10T10:00:00Z'});let serial=0;const id='qa-timing',key=()=>('timing-key-'+(++serial)).padEnd(24,'x');await service.seed({id,title:'QA',window:{start:'2026-09-01',end:'2026-09-30'},options:['a','b','c'].map(id=>({id,title:id}))});await service.setRound(id,'qa-admin',key(),{shortlist:['a','b','c']});await service.scheduleRound(id,'qa-admin',key(),{date:'2026-09-12'});return {store,service,id,key}}
test('shared resolver: explicit labels, Amsterdam exact timestamps, default only when absent, no end/default timestamp',()=>{const n={scheduledDate:'2026-09-12'};assert.deepEqual(resolvedEventTiming(n),{screening:'18:00'});assert.deepEqual(n,{scheduledDate:'2026-09-12'});assert.deepEqual(resolvedEventTiming({startsAt:'2026-09-12T17:30:00Z'}),{screening:'19:30'});assert.deepEqual(resolvedEventTiming({startsAt:'2026-12-12T17:30:00Z'}),{screening:'18:30'});assert.deepEqual(resolvedEventTiming({startsAt:'2026-09-12T17:30:00Z',timing:{screening:'20:15',end:'laat',arrival:'18:00'}}),{screening:'20:15',end:'laat'})});
test('round times persist through CAS, exact replay and stale-round/version guards; no ballot/deadline/default writes',async()=>{const f=await fixture(),before=structuredClone(f.store.row),p=await f.service.get(f.id);assert.equal(p.round.timing.screening,'18:00');assert.equal(f.store.row.roundSchedule.timing,undefined);const b={action:'times',eventId:'round-2026-09-12',eventVersion:0,expectedRoundId:p.round.id,timing:{screening:'19:45',end:''}},key=f.key();const result=await f.service.manageCoordination(f.id,'qa-admin',key,b);assert.equal((await f.service.get(f.id)).round.timing.screening,'19:45');assert.deepEqual(f.store.row.round,before.round);assert.deepEqual(f.store.row.votes,before.votes);assert.equal(f.store.row.roundSchedule.startsAt,undefined);assert.equal(f.store.row.roundSchedule.reminderMinutes,undefined);assert.deepEqual(await f.service.manageCoordination(f.id,'qa-admin',key,b),result);await assert.rejects(f.service.manageCoordination(f.id,'qa-admin',f.key(),b),e=>e.code==='event_changed');await assert.rejects(f.service.manageCoordination(f.id,'qa-admin',f.key(),{...b,eventVersion:1,expectedRoundId:'old-round'}),e=>e.code==='event_changed');await assert.rejects(f.service.manageCoordination(f.id,'wrong',f.key(),{...b,eventVersion:1}),e=>e.status===401)});
test('programme default projection and committed notice agree; edits preserve hidden arrival and reminder absence',async()=>{const f=await fixture();const {night}=await f.service.planNight(f.id,'qa-admin',f.key(),{selection:'pending',scheduledDate:'2026-09-13',choices:[]});const before=structuredClone(f.store.row);assert.deepEqual((await f.service.get(f.id)).programme[0].timing,{screening:'18:00'});assert.deepEqual(f.store.row,before);await f.service.manageCoordination(f.id,'qa-admin',f.key(),{action:'times',eventId:night.id,eventVersion:0,timing:{arrival:'17:00',screening:'',end:''}});let publicNight=(await f.service.get(f.id)).programme[0];assert.deepEqual(publicNight.timing,{screening:'18:00'});assert.deepEqual(f.store.row.coordinationEvents.at(-1).timing,publicNight.timing);await f.service.manageCoordination(f.id,'qa-admin',f.key(),{action:'times',eventId:night.id,eventVersion:1,timing:{screening:'20:00',end:'22:00'}});publicNight=(await f.service.get(f.id)).programme[0];assert.deepEqual(publicNight.timing,{screening:'20:00',end:'22:00'});assert.deepEqual(f.store.row.coordinationEvents.at(-1).timing,publicNight.timing);assert.equal(f.store.row.programme[0].timing.arrival,'17:00');assert.equal(publicNight.startsAt,undefined);assert.equal(publicNight.reminderMinutes,undefined)});
test('resolved new programme keeps round-specific explicit time',async()=>{const f=await fixture(),r=(await f.service.get(f.id)).round;await f.service.manageCoordination(f.id,'qa-admin',f.key(),{action:'times',eventId:'round-2026-09-12',expectedRoundId:r.id,eventVersion:0,timing:{screening:'19:15'}});const change=async(action,extra={})=>{const r=(await f.service.get(f.id)).round;return f.service.setRound(f.id,'qa-admin',f.key(),{action,expectedRoundId:r.id,expectedRevision:r.revision,...extra})};await change('close');await change('resolve',{choice:'a',programme:true});assert.equal((await f.service.get(f.id)).programme[0].timing.screening,'19:15')});

test('linking an existing timed evening keeps its explicit Amsterdam start',async()=>{const f=await fixture(),r=(await f.service.get(f.id)).round;await f.service.manageCoordination(f.id,'qa-admin',f.key(),{action:'times',eventId:'round-2026-09-12',expectedRoundId:r.id,eventVersion:0,timing:{screening:'19:15'}});const {night}=await f.service.planNight(f.id,'qa-admin',f.key(),{selection:'pending',startsAt:'2026-09-12T18:30:00Z',choices:[]});const change=async(action,extra={})=>{const r=(await f.service.get(f.id)).round;return f.service.setRound(f.id,'qa-admin',f.key(),{action,expectedRoundId:r.id,expectedRevision:r.revision,...extra})};await change('close');await change('resolve',{choice:'a',programme:true,programmeId:night.id});assert.equal((await f.service.get(f.id)).programme[0].timing.screening,'20:30')});
