import test from 'node:test';import assert from 'node:assert/strict';
import {createApi} from './api.mjs';import {openState,emptyState} from './state.mjs';import {createPlanningService} from './runtime/planning/service.mjs';
async function fixture(){const c=openState(emptyState()),s=createPlanningService({store:c.plans,adminToken:'secret'});await s.seed({id:'proof',title:'Test',window:{start:'2026-09-01',end:'2026-09-30'},options:['a','b','c','d','e','f'].map(id=>({id,title:id}))});await s.setRound('proof','secret','initial-round-key01',{shortlist:['a','b','c']});const store={data:c.export(),etag:1,async getWithMetadata(){return {data:structuredClone(this.data),etag:String(this.etag)}},async setJSON(k,v,{onlyIfMatch}){if(onlyIfMatch!==String(this.etag))return {modified:false};this.data=structuredClone(v);this.etag++;return {modified:true}}};c.close();let code;const ids=[];const opts={store,blobs:{},adminToken:'secret',organizerIds:ids,origin:'https://example.test',queueMail:async(c,m)=>{code=m.code},now:()=> '2026-09-08T20:00:00.000Z'};let api=createApi(opts);
async function request(path,method='GET',body,headers={}){const r=await api(new Request('https://example.test/filmmaand/api/'+path,{method,headers:{Origin:'https://example.test',...headers},...(body?{body:JSON.stringify(body)}:{})}),{ip:'fixture'});return {status:r.status,body:await r.json(),headers:r.headers}}
async function account(email,avatar){const ch=await request('auth/code','POST',{email}),login=await request('auth/verify','POST',{challengeId:ch.body.challengeId,code});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0],id=login.body.participant.id;const p=await request('auth/profile','PUT',{expectedRevision:0,name:email[0],animal:'otter',avatarId:avatar},{Cookie:cookie,'Idempotency-Key':'profile-key-'+avatar+'-00000'});assert.equal(p.status,200);return {cookie,id}}
const a=await account('a@example.test',4),b=await account('b@example.test',7);const headers=(who,key)=>({Cookie:who.cookie,'Idempotency-Key':key,'X-Filmmaand-Organizer-Id':who.id,'X-Filmmaand-Reset-Generation':'generation-1'});store.data.resetGeneration='generation-1';return {store,ids,a,b,request,headers,reconfigure:v=>{api=createApi({...opts,organizerIds:v})}}}

test('organizer defaults deny; validated cookie, CSRF and generation gate every mutation',async()=>{const f=await fixture();assert.equal((await f.request('organizer')).status,401);assert.equal((await f.request('organizer','GET',null,{Cookie:f.a.cookie})).status,403);f.ids.push(f.a.id);const access=await f.request('organizer','GET',null,{Cookie:f.a.cookie});assert.equal(access.body.participantId,f.a.id);assert.equal(access.body.resetGeneration,'generation-1');assert.equal(JSON.stringify(access.body).includes('secret'),false);const round=(await f.request('plans/proof')).body.round,body={action:'deadline',expectedRoundId:round.id,expectedRevision:round.revision,closesAt:'2026-09-09T20:00:00Z'},h=f.headers(f.a,'deadline-request-001');assert.equal((await f.request('plans/proof/round','POST',body,{...h,Origin:''})).status,403);assert.equal((await f.request('plans/proof/round','POST',body,{...h,'X-Filmmaand-Reset-Generation':'old'})).body.error.code,'reset_generation');assert.equal((await f.request('plans/proof/round','POST',body,{...h,'X-Filmmaand-Organizer-Id':f.b.id})).body.error.code,'organizer_changed');assert.equal((await f.request('plans/proof/round','POST',body,{...h,'Idempotency-Key':'bad'})).status,400);assert.equal((await f.request('plans/proof/round','POST',body,h)).status,200);});

test('receipt replay is account-bound; revoke/expiry/reset reject before receipt, bearer admin remains separate',async()=>{const f=await fixture();f.ids.push(f.a.id,f.b.id);const round=(await f.request('plans/proof')).body.round,body={action:'deadline',expectedRoundId:round.id,expectedRevision:round.revision,closesAt:'2026-09-09T20:00:00Z'},key='shared-client-key-001',h=f.headers(f.a,key);const saved=await f.request('plans/proof/round','POST',body,h);assert.equal(saved.status,200);const replay=await f.request('plans/proof/round','POST',body,h);assert.deepEqual(replay.body,saved.body);const other=await f.request('plans/proof/round','POST',body,f.headers(f.b,key));assert.equal(other.status,409);assert.equal(other.body.error.code,'round_conflict');assert.equal((await f.request('plans/proof/round','POST',body,{...f.headers(f.b,key),'X-Filmmaand-Organizer-Id':f.a.id})).body.error.code,'organizer_changed');f.reconfigure([f.b.id]);assert.equal((await f.request('plans/proof/round','POST',body,h)).status,403);f.reconfigure([f.a.id,f.b.id]);f.store.data.resetGeneration='generation-2';assert.equal((await f.request('plans/proof/round','POST',body,h)).body.error.code,'reset_generation');f.store.data.resetGeneration='generation-1';for(const session of f.store.data.auth.sessions)if(session.participant_id===f.a.id)session.expires_at='2026-09-08T19:00:00Z';assert.equal((await f.request('plans/proof/round','POST',body,h)).status,401);const current=(await f.request('plans/proof')).body.round;const closed=await f.request('plans/proof/round','POST',{action:'close',expectedRoundId:current.id,expectedRevision:current.revision},{Authorization:'Bearer secret','Idempotency-Key':'bearer-admin-close01'});assert.equal(closed.status,200);assert.equal(closed.body.round.status,'closed');});
