import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {emptyState,openState} from './state.mjs';
import {createPlanningService} from './runtime/planning/service.mjs';
const movie={id:'tt0078748',title:'Alien',year:1979};
const actor='a'.repeat(43),other='b'.repeat(43),body={movieId:movie.id,detail:'Together'};
async function fixture(){const c=openState(emptyState());const s=createPlanningService({store:c.plans,adminToken:'fixture',movieCatalogue:{get:id=>id===movie.id?movie:null}});const seed=JSON.parse(await readFile(new URL('./runtime/planning/seed.json',import.meta.url)));seed.id='autolike-fixture';await s.seed(seed);return {c,s,id:seed.id}}
test('movie suggestion atomically likes once, preserving dates/rank/others/votes and old receipts',async()=>{const {c,s,id}=await fixture();try{await s.submit(id,actor,'existing-own-0001',{expectedRevision:0,name:'First',choices:['blade','lynch'],rankingOrder:['lynch','blade'],dates:['2026-09-12']});await s.submit(id,other,'existing-other-01',{expectedRevision:0,name:'Other',choices:['blade'],dates:[]});const before=c.export().plans[id].data,result=await s.suggest(id,actor,'movie-success-01',body),after=c.export().plans[id].data;const response=(await s.own(id,actor)).response;assert.deepEqual(response.choices,['blade','lynch',result.option.id]);assert.deepEqual(response.rankingOrder,['lynch','blade']);assert.deepEqual(response.dates,['2026-09-12']);assert.equal(response.name,'First');assert.equal(response.revision,2);for(const [key,value]of Object.entries(before.responses))if(value.name==='Other')assert.deepEqual(after.responses[key],value);assert.deepEqual(after.votes,before.votes);assert.deepEqual(after.round,before.round);for(const [k,v]of Object.entries(before.receipts))assert.deepEqual(after.receipts[k],v);assert.equal(result.autoLiked,true)}finally{c.close()}});
test('concurrent/lost ACK exact replay creates one option/like and never relikes after explicit removal',async()=>{const {c,s,id}=await fixture();try{const [a,b]=await Promise.all([s.suggest(id,actor,'movie-replay-001',body),s.suggest(id,actor,'movie-replay-001',body)]);assert.deepEqual(a,b);let response=(await s.own(id,actor)).response;assert.deepEqual(response.choices,[a.option.id]);assert.equal(response.revision,1);await s.submit(id,actor,'remove-after-001',{expectedRevision:response.revision,choices:[],dates:[]});const before=c.export();assert.deepEqual(await s.suggest(id,actor,'movie-replay-001',body),a);assert.deepEqual(c.export(),before);await assert.rejects(s.suggest(id,actor,'movie-replay-001',{...body,detail:'different'}),e=>e.code==='key_reused')}finally{c.close()}});
test('duplicate and invalid movie fail without any like or option mutation; themes do not autolike',async()=>{const {c,s,id}=await fixture();try{await s.suggest(id,actor,'original-movie-01',body);let before=c.export();await assert.rejects(s.suggest(id,other,'duplicate-movie1',body),e=>e.code==='duplicate');await assert.rejects(s.suggest(id,other,'invalid-movie-01',{movieId:'tt9999999'}),e=>e.code==='movie');assert.deepEqual(c.export(),before);const theme=await s.suggest(id,other,'theme-unchanged1',{title:'A theme',movieIds:[movie.id]});assert.equal(theme.autoLiked,undefined);assert.deepEqual((await s.own(id,other)).response.choices,[])}finally{c.close()}});
test('full favourites capacity rejects whole movie suggestion rather than dropping existing likes',async()=>{const {c,s,id}=await fixture();try{const row=await c.plans.read(id);row.data.maxChoices=1;await c.plans.compareAndSwap(id,row.etag,row.data);await s.submit(id,actor,'capacity-own-001',{expectedRevision:0,choices:['blade'],dates:[]});const before=c.export();await assert.rejects(s.suggest(id,actor,'capacity-movie01',body),e=>e.code==='choices');assert.deepEqual(c.export(),before)}finally{c.close()}});

import vm from 'node:vm';
const pickerSource=await readFile(new URL('../public/filmmaand/picker/picker.js',import.meta.url),'utf8');
const sendSource=pickerSource.slice(pickerSource.indexOf('async function sendSuggestion()'),pickerSource.indexOf('\n',pickerSource.indexOf('async function sendSuggestion()')));
async function clientCase({pending=false,removed=false}={}){const ctx=vm.createContext({crypto:{randomUUID:()=> 'client-key-00001'},clearTimeout(){},JSON,busy:false,saving:false,receipt:pending?{}:null,saveTimer:0,suggestionDraft:{mode:'film',movie,title:'Alien',detail:'Note'},suggestionReceipt:{key:'client-key-00001',body},suggestionError:'',suggested:null,displayProfile:null,window:{},own:{revision:2,choices:['blade'],dates:['2026-09-12'],rankingOrder:['blade']},draft:{choices:['blade','lynch'],dates:['2026-09-14'],rankingOrder:['lynch','blade']},error:'',calls:[],read(){return null},write(){return true},render(){},existingMovie(){return null},persist(){},changed(){return true},ownDraft(){throw Error('dirty draft must not be replaced')},settled(){return false},refresh:async()=>{},scheduleSave(){},request:async function(path){ctx.calls.push(path);return path==='/suggestions'?{option:{id:'new'},autoLiked:true}:{response:{revision:3,choices:removed?['blade']:['blade','new'],dates:['2026-09-12'],rankingOrder:['blade']}}}});vm.runInContext(sendSource,ctx);await ctx.sendSuggestion();return ctx;}
test('confirmed client merge preserves dirty date/order edits and does not restore later removed like',async()=>{const c=await clientCase();assert.deepEqual([...c.draft.choices],['blade','lynch','new']);assert.deepEqual([...c.draft.dates],['2026-09-14']);assert.deepEqual([...c.draft.rankingOrder],['lynch','blade']);assert.equal(c.suggestionReceipt,null);const removed=await clientCase({removed:true});assert.deepEqual([...removed.draft.choices],['blade','lynch']);});
test('pending personal receipt blocks suggestion without replacing either receipt',async()=>{const c=await clientCase({pending:true});assert.deepEqual(c.calls,[]);assert.equal(c.suggestionReceipt.key,'client-key-00001');assert.match(c.suggestionError,/openstaande/)});
