import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {emptyState,openState} from './state.mjs';
import {createPlanningService} from './runtime/planning/service.mjs';
const a={id:'tt0078748',title:'Alien',year:1979,runtime:117,poster:'https://image.tmdb.org/t/p/w500/alien.jpg',backdrop:'https://image.tmdb.org/t/p/original/alien.jpg',overview:'Never the theme synopsis',rating:8.5};
const b={id:'tt0090605',title:'Aliens',year:1986,poster:'https://m.media-amazon.com/images/M/aliens@._V1_QL75_UX600_.jpg'};
const actor='a'.repeat(43),body={title:'Een avond in de ruimte',detail:'Samen kijken',movieIds:[b.id,a.id]};
async function fixture(){const c=openState(emptyState()),movies=new Map([[a.id,a],[b.id,b]]);const s=createPlanningService({store:c.plans,adminToken:'fixture',movieCatalogue:{get:id=>movies.get(id)},imageStore:{owned:async(actor,id)=>id==='owned-image'}});const seed=JSON.parse(await readFile(new URL('./runtime/planning/seed.json',import.meta.url)));seed.id='theme-fixture';await s.seed(seed);return {c,s,id:seed.id,movies}}
test('canonical ordered lineup persists; no single-movie metadata or preference mutation',async()=>{const {c,s,id}=await fixture();try{await s.submit(id,actor,'existing-draft-0001',{expectedRevision:0,name:'Test',choices:['blade'],dates:['2026-09-12']});const round=(await s.voteView(id,actor)).round;await s.vote(id,actor,'existing-vote-00001',{expectedRevision:0,final:round.shortlist[0]});const before=c.export().plans[id].data;const result=await s.suggest(id,actor,'theme-composer-001',body),o=result.option;assert.deepEqual(o.movies.map(m=>m.id),body.movieIds);assert.deepEqual(o.lineup,['Aliens','Alien']);assert.equal(o.movie,undefined);assert.equal(o.movies[1].rating,undefined);assert.equal(o.movies[1].overview,undefined);assert.match(o.image.caption,/Aliens/);const after=c.export().plans[id].data;for(const k of ['responses','votes','round','roundSchedule','displayProfiles'])assert.deepEqual(after[k],before[k]);for(const [k,v]of Object.entries(before.receipts))assert.deepEqual(after.receipts[k],v);assert.deepEqual((await s.get(id)).options.at(-1).movies,o.movies)}finally{c.close()}});
test('lost acknowledgement/concurrent exact retries append once; order is in receipt fingerprint',async()=>{const {c,s,id}=await fixture();try{const first=await s.suggest(id,actor,'theme-lost-ack-0001',body);const state=c.export();const retries=await Promise.all([s.suggest(id,actor,'theme-lost-ack-0001',body),s.suggest(id,actor,'theme-lost-ack-0001',body)]);assert.deepEqual(retries,[first,first]);assert.deepEqual(c.export(),state);await assert.rejects(s.suggest(id,actor,'theme-lost-ack-0001',{...body,movieIds:[...body.movieIds].reverse()}),e=>e.code==='key_reused');assert.deepEqual(c.export(),state)}finally{c.close()}});
test('invalid/mixed/unknown/duplicate/oversized lists reject without writes',async()=>{const {c,s,id}=await fixture();try{const state=c.export();for(const patch of [{movieId:a.id},{movieIds:[]},{movieIds:[a.id,a.id]},{movieIds:['tt9999999']},{movieIds:['wrong']},{movieIds:null},{movieIds:Array.from({length:13},(_,i)=>'tt'+String(1000000+i))},{title:'<script>'}])await assert.rejects(s.suggest(id,actor,'theme-invalid-0001',{...body,...patch}),e=>e.status===400);assert.deepEqual(c.export(),state)}finally{c.close()}});
test('owned upload wins, unsafe catalogue artwork excluded, legacy themes still save',async()=>{const {c,s,id,movies}=await fixture();try{const image=(await s.suggest(id,actor,'theme-upload-0001',{...body,imageId:'owned-image'})).option.image;assert.equal(image.id,'owned-image');assert.equal(image.caption,undefined);await assert.rejects(s.suggest(id,actor,'theme-upload-0002',{...body,title:'Other',imageId:'foreign'}),e=>e.code==='image');movies.set(a.id,{...a,poster:'https://evil.example/a',backdrop:'javascript:alert(1)'});const safe=(await s.suggest(id,actor,'theme-unsafe-0001',{title:'Safe',movieIds:[a.id]})).option;assert.equal(safe.image,undefined);assert.equal(safe.movies[0].poster,null);const legacy=(await s.suggest(id,actor,'theme-legacy-0001',{title:'Gameavond',detail:''})).option;assert.equal(legacy.movies,undefined);assert.equal(legacy.movie,undefined)}finally{c.close()}});

test('saved per-film artwork survives a cold catalogue cache',async()=>{const {c,s,id,movies}=await fixture();try{const saved=(await s.suggest(id,actor,'theme-cold-cache-01',body)).option;movies.set(a.id,{id:a.id,title:a.title,year:a.year});movies.set(b.id,{id:b.id,title:b.title,year:b.year});const out=(await s.get(id)).options.at(-1);assert.deepEqual(out.movies,saved.movies);assert.deepEqual(out.image,saved.image)}finally{c.close()}});

test('simultaneous first submissions with one receipt create one option',async()=>{const {c,s,id}=await fixture();try{const results=await Promise.all([s.suggest(id,actor,'theme-concurrent-001',body),s.suggest(id,actor,'theme-concurrent-001',body)]);assert.deepEqual(results[0],results[1]);assert.equal((await s.get(id)).options.filter(o=>o.id===results[0].option.id).length,1)}finally{c.close()}});
