// /filmmaand/wanneer/: the date poll as a group chat. Two halves:
//  1. what ships: generated from the invitation kit, no sample people, no pass leaks, the site's reset guard first;
//  2. the exact API flow the page performs: mail link → pass GET → PUT (Idempotency-Key, revision) → re-GET shows your own
//     name; "Ik kan deze week niet" = all false = declined; a dead pass falls back to the session.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createApi} from './api.mjs';import {openState,emptyState} from './state.mjs';import {createPlanningService} from './runtime/planning/service.mjs';
import handler from './handler.mjs';import vm from 'node:vm';

const dir=new URL('../public/filmmaand/wanneer/',import.meta.url);
const page=await readFile(new URL('index.html',dir),'utf8'),js=await readFile(new URL('wanneer.js',dir),'utf8'),eggs=await readFile(new URL('eggs.js',dir),'utf8'),games=await readFile(new URL('games.js',dir),'utf8');
// The kit's sample people (appje2 CREW) and earlier demo names. None may reach production.
const SAMPLE=['Bas','Koen','Fre','Ruben','Lucas','Joeri','Sjoerd','Noor','Sam','Jules'];

// Chris, 23 Sept: "make sure we don't accidentally load the page first before the movie if they haven't seen it. this is vital".
test('first-time visitors never see the page before the film: a black curtain is the first thing painted, and it always comes down',async()=>{
 if(/film-mode\.js/.test(page))return;// the curtain ships only with FILM_MODE 'first-visit'
 const curtainJs=await readFile(new URL('film-curtain.js',dir),'utf8'),loader=await readFile(new URL('film-loader.js',dir),'utf8');
 assert.match(page,/<body><div id="afm-curtain" aria-hidden="true"><\/div>/,'the curtain is the first element in <body>');
 assert.match(page,/#afm-curtain\{position:fixed;inset:0;z-index:2147482999;background:#000;animation:afm-curtain-safe [^}]* 10s forwards\}/,'opaque, under the film (2147483000), with the 10 s failsafe');
 assert.match(page,/@keyframes afm-curtain-safe\{to\{opacity:0;visibility:hidden\}\}/);
 assert.match(page,/@media \(prefers-reduced-motion:reduce\)\{#afm-curtain\{display:none\}\}/);
 assert.ok(page.indexOf('film-curtain.js')<page.indexOf('</head>'),'decided in <head>, before the first paint');
 assert.match(curtainJs,/\[\?&\]\(pas\|film\)/,'a mail link (or ?film) always gets the curtain, even on a device that has seen the film');
 assert.match(curtainJs,/rel="preload";l\.as="script";l\.href="\/filmmaand\/wanneer\/film\.bundle\.js"/,'the bundle starts downloading right away');
 // the loader takes it down on every path: seen, error, the film (under its overlay), failsafe
 for(const re of [/seen === true\) \{ unmark\(\); return lift\(\); \}/,/s\.onerror = function \(\) \{ unmark\(\); lift\(\); \}/,/lift\(!!h\)/,/afm-curtain-safe'\) lift\(true\)/,/mark = function \(\) \{ if \(!shows\(\)\) busy = true; \}/])
  assert.match(loader,re);
});

test('the shipped page is the generated kit page, without sample people or kit state',()=>{
 assert.match(page,/^<!doctype html><html lang="nl"><head><script src="\/filmmaand\/identity\/reset-guard.js"><\/script>/);
 assert.match(page,/GENERATED by scripts\/build-wanneer\.mjs/);assert.match(eggs,/^\/\/ GENERATED by scripts\/build-wanneer\.mjs/);assert.match(games,/^\/\/ GENERATED by scripts\/build-wanneer\.mjs/);
 for(const [name,text] of [['index.html',page],['wanneer.js',js],['eggs.js',eggs],['games.js',games]]){
  for(const n of SAMPLE)assert.equal(new RegExp('\\b'+n+'\\b').test(text),false,name+' names '+n);
  assert.equal(/afm-groepsapp|CREW/.test(text),false,name+' carries the kit fixture/state');
  assert.equal(/data:image\/(png|jpe?g|webp);base64/.test(text),false,name+' inlines a raster image');
 }
 assert.match(page,/<span id="sub">Alec, jij<\/span>/);
 // Exactly these scripts, in this order: the guard (head), avatars, the page. eggs.js is started by wanneer.js after the first GET.
 // + Cairn's intro film (Chris, 23 Sept): an optional mode file, then the loader, which fetches film.bundle.js itself (async).
 const film=/film-mode\.js/.test(page)?['/filmmaand/wanneer/film-mode.js','/filmmaand/wanneer/film-loader.js']:['/filmmaand/wanneer/film-loader.js'];
 // + the chat games (Capsule, 23 Sept): games.js straight after the page, so window.filmmaandGames exists before eggs.js renders.
 const curtain=/film-curtain\.js/.test(page)?['/filmmaand/wanneer/film-curtain.js']:[];
 assert.deepEqual([...page.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),['/filmmaand/identity/reset-guard.js',...curtain,'/filmmaand/identity/avatars.js','/filmmaand/wanneer/wanneer.js','/filmmaand/wanneer/games.js',...film]);
 // games.js only talks to the chat through window.filmmaandChat: no network, no storage of its own.
 assert.equal(/localStorage|sessionStorage|document\.cookie|indexedDB|fetch\(|XMLHttpRequest|sendBeacon|WebSocket/.test(games),false,'games.js reaches past window.filmmaandChat');
 assert.equal(/<script>/.test(page),false);
 assert.match(page,/<meta name="referrer" content="no-referrer">/);
 assert.ok(page.includes('#rsvp button[data-pre=true]:not([aria-pressed=true]){border:1.5px dashed #00a884;background:#f0fbf7}'));assert.ok(page.includes('@media (prefers-color-scheme:dark){#rsvp button[data-pre=true]:not([aria-pressed=true]){background:#103529}}'));
 assert.match(js,/Klopt dit\? Tik op je antwoord om het door te geven\./);
 // Voters see the RSVP buttons too: the kit's body.voted rule hides .quick/.sub, the page overrides it for #rsvp.
 assert.ok(page.includes('body.voted #rsvp .quick{display:flex}body.voted #rsvp .sub{display:block}'));
 assert.match(js,/pickedAt:data\?\.pickedAt\|\|null,mine/);assert.match(js,/canSend:chatOpenNow\(\),pickedAt:data\?\.pickedAt\|\|null/);
 for(const id of ['poll','nights','go','all','none','sys','note','tally','sub','prev','m1','typing','rsvp','rsvp-ja','rsvp-nee','rsvp-sub'])assert.ok(page.includes(`id="${id}"`),id);
 for(const src of page.matchAll(/src="(\/filmmaand\/assets\/[^"]+)"/g))assert.ok(src[1].startsWith('/filmmaand/assets/wanneer-pudding-'));
});

test('the page keeps the pass in tab history and sends it as the header, never in a URL or persistent storage',()=>{
 assert.equal(/localStorage|sessionStorage|document\.cookie|indexedDB/.test(js),false);
 assert.equal(/Authorization|Bearer/.test(js),false);
 assert.match(js,/headers\['X-Filmmaand-Poll-Pass'\]=pass/);
 assert.match(js,/searchParams\.delete\('pas'\);history\.replaceState/);
 // The pass is taken out of the URL before the first request is made.
 assert.ok(js.indexOf("history.replaceState")<js.indexOf('fetch('));
 assert.match(js,/const API='\/filmmaand\/api\/plans\/home-picker-lab\/date-poll'/);
 // The token never goes into a URL: the one fetch goes to the fixed API constant.
 assert.deepEqual(js.match(/fetch\([^,]*,/g),['fetch(url,']);assert.match(js,/async function call\(method,body,key,url=API\)/);
 // URLs: the four fixed endpoints (+ the intro film's own flag, 23 Sept) and one numeric chat cursor; nothing else is ever put in a URL.
 assert.deepEqual(js.match(/API\s*\+[^;,)]*/g),["API+'-doodle'","API+'-chat'","API+'-rsvp'","API+'-film'","API+'-login'","API+'?since='+since:API","API+'?since='+chatCursor","API+'?since='+chatCursor+'&lite=1'"]);
 assert.match(js,/const since=chatCursor;/);assert.match(js,/chatCursor=Math\.max\(chatCursor,c\.cursor\|\|0\)/);
 assert.deepEqual(js.match(/,DOODLE_API\)/g),[',DOODLE_API)']);assert.deepEqual(js.match(/CHAT_API\+'\?since='\+chatCursor\)/g),["CHAT_API+'?since='+chatCursor)"]);
 assert.equal((js.match(/call\('POST'/g)||[]).length,2);// the chat send + the one silent auto-login (Chris, 23 Sept):
 // only with a pass, once per page load, to the fixed LOGIN_API, with an empty body (the pass travels in the header).
 assert.match(js,/if\(pass&&!autoLogged\)\{const login=await call\('POST',\{\},newKey\(\),LOGIN_API\)/);
 // A caller-supplied Idempotency-Key (Capsule: one stable key per message, reused on retries) is validated like any key.
 assert.match(js,/const KEY_RE=\/\^\[A-Za-z0-9_-\]\{16,100\}\$\/;/);assert.match(js,/acceptsKey:true/);
 assert.match(js,/if\(given!==undefined&&!KEY_RE\.test\(given\)\)throw/);assert.match(js,/const key=given\?\?newKey\(\);/);
 // ?antwoord= only pre-selects: sendRsvp (the only RSVP write) is reached from the two buttons alone.
 assert.deepEqual(js.match(/sendRsvp\(a\)|sendRsvp\(answer,true\)/g),['sendRsvp(answer,true)','sendRsvp(a)']);assert.equal(/preselect[^;\n]*sendRsvp/.test(js),false);
 // Nothing writes on load: the only PUT is inside saveOnce, reached from a tap (Klaar / a night / the quick buttons).
 assert.equal((js.match(/call\('PUT'/g)||[]).length,4);// the vote (saveOnce), the doodle (filmmaandDoodles.save), the rsvp (a tap), the film flag:
 // the intro film's "seen" flag is written ONLY from the film's own end callback, and only for a completed viewing (never on load, never on a skip).
 assert.match(js,/window\.AFM_FILM_ONDONE=r=>\{if\(r&&r\.completed\)window\.filmmaandFilm\.markSeen\(\)\};/);
 assert.equal((js.match(/markSeen\(/g)||[]).length,2);// its definition + that one caller
});

test('cadence B: no polling loop; re-GETs only on open, visible/focus (15s), and two bounded ones after a doodle send',()=>{
 // The one interval is the send-button wiggle (UI only). It never requests.
 const intervals=[...js.matchAll(/setInterval\(([^;]*)\)/g)].map(m=>m[1]);
 assert.equal(intervals.length,1);assert.match(intervals[0],/wiggle/);assert.equal(/load\(|call\(|fetch\(/.test(intervals[0]),false);
 // Timed reads: exactly the +20s/+60s pair after a doodle send, only for a visible tab.
 assert.match(js,/\[20e3,60e3\]\.map\(ms=>setTimeout\(\(\)=>\{if\(document\.visibilityState==='visible'/);
 // Exactly one bounded timed read outside hot mode: the +20 s / +60 s pair after a send.
 assert.equal((js.match(/setTimeout\(\(\)=>\{if\(document\.visibilityState==='visible'&&!dirty\(\)&&!saving\)load\(\)\}/g)||[]).length,1);
 assert.match(js,/Date\.now\(\)-lastRead<15e3\)return;load\(\)/);
 // + filmmaandChat.refresh() (games.js, when a game closes): untimed, the same guards, at most one read per 5 s.
 assert.match(js,/refresh\(\)\{if\(anon\|\|document\.visibilityState!=='visible'\|\|!loaded\|\|!data\|\|dirty\(\)\|\|saving\|\|Date\.now\(\)-lastRead<5e3\)return false;load\(\);return true\}/);
 assert.equal((js.match(/\brefresh\(\)/g)||[]).length,1,'refresh() has one definition and no timed caller in the page');
 assert.match(js,/addEventListener\('visibilitychange',fresh\);window\.addEventListener\('focus',fresh\)/);
 // Hot mode (Chris; Cameo's guardrails): the only other timed read. It is a LITE read, wired through createHot() (tested
 // behaviourally below); hidden/blur pause it; the server clock (Date header) decides freshness.
 assert.match(js,/API\+'\?since='\+chatCursor\+'&lite=1'/);assert.match(js,/skew=served-Date\.now\(\)/);
 assert.match(js,/if\(document\.visibilityState==='visible'\)hot\.loop\(\);else hot\.pause\(\)/);assert.match(js,/window\.addEventListener\('blur',\(\)=>hot\.pause\(\)\)/);
 assert.match(js,/read:\(\)=>dirty\(\)\|\|saving\?Promise\.resolve\(null\):liteLoad\(\)/);
 assert.match(js,/function load\(\)\{return readGate\.full\(fullRead\)\}/);
 assert.match(js,/function liteLoad\(\)\{return readGate\.lite\(liteRead\)\}/);
 assert.match(js,/if\(b\.pollId!==pollId\|\|b\.status!==poll\(\)\?\.status\|\|b\.doodleStamp!==stamp\(data\?\.doodles\)\)return await fullRead\(\)/);
 assert.equal((js.match(/liteLoad\(\)(?!\{)/g)||[]).length,1);// one call site (plus its definition)assert.equal((js.match(/setTimeout\(f,ms\)/g)||[]).length,1);
});

test('hot-mode scheduler (unit): 15 s hot, 60 s cold, 20-min idle cap, backoff 30 s / 60 s',()=>{
 const src=/const HOT_MS=[^\n]*\n(?:\/\/[^\n]*\n)*(function hotDelay[\s\S]*?\n\})/.exec(js);assert.ok(src,'hotDelay not found');
 const box={};vm.runInNewContext(js.match(/const HOT_MS=[^\n]*/)[0]+'\n'+src[1]+';this.d=hotDelay',box);const d=box.d;
 const base={voted:true,visible:true,focused:true,chatOpen:true,newestAge:10e3,sinceActive:60e3,fails:0};
 assert.equal(d(base),15e3);
 for(const [k,v] of [['voted',false],['visible',false],['focused',false],['chatOpen',false],['sinceActive',20*60e3+1]])assert.equal(d({...base,[k]:v}),null,k+'='+v);
 for(const age of [120e3,Infinity,NaN])assert.equal(d({...base,newestAge:age}),60e3,'cold age '+age);
 assert.equal(d({...base,newestAge:119e3}),15e3);assert.equal(d({...base,sinceActive:20*60e3}),15e3);
 // Alec's opening sticker never counts as fresh; the state passes the page's own vote flag.
 assert.match(js,/if\(!chatMsgs\[i\]\.alec\)return Date\.now\(\)\+skew-Date\.parse\(chatMsgs\[i\]\.at\)/);assert.match(js,/state:\(\)=>\(\{voted,visible:document\.visibilityState==='visible'/);
 assert.equal(d({...base,fails:1}),30e3);assert.equal(d({...base,fails:2}),60e3);assert.equal(d({...base,fails:3}),null);
});

test('no working link and no login: the page sends you to the login page (and back here), never an anonymous poll',()=>{
 // Chris, 23 Sept: "when you're not logged in you shouldn't be able to access the wanneer page entirely".
 assert.match(js,/if\(!saving&&!loaded&&!anon\)\{location\.replace\('\/filmmaand\/identity\/\?terug=\/filmmaand\/wanneer\/'\);return false\}/);
 assert.equal(/anonPoll|\?public=1/.test(js),false,'the anonymous public poll is gone');
 // A dead pass with a live session retries with the session before any of this (dropPass → load()).
 assert.match(js,/if\(attempt===0&&dropPass\(e\)\)continue;return trouble\(e\)/);
 assert.equal(/lives in memory only/.test(js),false,'stale comment gone: the pass survives a reload via history.state');
});

test('hot mode, behaviourally with a fake clock: 15-s cadence, 20-min no-input cap, resume on input, backoff, voters only',async()=>{
 const code=js.match(/const HOT_MS=[^\n]*/)[0]+'\n'+/(function hotDelay[\s\S]*?\n\})/.exec(js)[1]+'\n'+/(function createHot[\s\S]*?\n\}\n)/.exec(js)[1];
 function sim({voted=true,visible=true,messages=true,serverNewAt=Infinity,readResult=()=>true}={}){
  let clock=0,timer=null,reads=0,lastMsg=0;const box={};
  vm.runInNewContext(code+';this.createHot=createHot',box);
  const hot=box.createHot({now:()=>clock,setT:(f,ms)=>{timer={f,at:clock+ms};return 1},clearT:()=>{timer=null},
   state:()=>({voted,visible,focused:true,chatOpen:true,newestAge:clock-lastMsg}),read:async()=>{reads++;if(clock>=serverNewAt&&lastMsg<serverNewAt)lastMsg=clock;return readResult(reads)}});
  // Someone keeps chatting: a new message every 60 s, so the chat stays "fresh" the whole time.
  async function run(ms){const end=clock+ms;while(true){const next=Math.min(timer?timer.at:Infinity,Math.ceil((clock+1)/60e3)*60e3);if(next>end){clock=end;break}
   clock=next;if(messages&&clock%60e3===0)lastMsg=clock;if(timer&&timer.at===clock){const f=timer.f;timer=null;await f()}}}
  return {hot,run,reads:()=>reads,armed:()=>hot.armed,now:()=>clock,set:v=>{visible=v}};
 }
 // 1) No input at all: 15 s reads for 20 minutes, then nothing, although messages keep coming.
 const a=sim();a.hot.loop();await a.run(20*60e3);const at20=a.reads();assert.ok(at20>=79&&at20<=81,'reads in 20 min: '+at20);
 // The cap is checked on each tick, so it stops within a tick or two of 20:00, and then stays off.
 await a.run(60e3);const at21=a.reads();assert.ok(at21-at20<=2,'after 20:00: '+(at21-at20));
 await a.run(9*60e3);assert.equal(a.reads(),at21,'no reads from minute 21 to 30');assert.equal(a.armed(),false);
 // 2) A tap or key resumes it at once, with a fresh 20-minute window.
 a.hot.input();assert.equal(a.armed(),true);const r=a.reads();await a.run(60e3);assert.ok(a.reads()-r>=3,'resumed: '+(a.reads()-r));
 // 3) Input every 5 minutes keeps it going past 20 minutes.
 const b=sim();b.hot.loop();for(let i=0;i<8;i++){await b.run(5*60e3);b.hot.input()}assert.ok(b.reads()>=157,'with input: '+b.reads());
 // 4) Errors back off 30 s, then 60 s, then stop (cadence B takes over).
 const c=sim({readResult:()=>false});c.hot.loop();await c.run(15e3);assert.equal(c.reads(),1);await c.run(30e3);assert.equal(c.reads(),2);
 await c.run(60e3);assert.equal(c.reads(),3);await c.run(60e3);assert.equal(c.reads(),3);assert.equal(c.armed(),false);
 // 5) Not voted (the chat isn't on screen) or a hidden tab: never a single read.
 const d=sim({voted:false});d.hot.loop();await d.run(5*60e3);assert.equal(d.reads(),0);
 const h=sim({visible:false});h.hot.loop();await h.run(5*60e3);assert.equal(h.reads(),0);
 // 6) A quiet open tab keeps a slow cold check. A message posted after a long lull is
 // discovered within 60 s and the next check returns to the 15 s hot cadence.
 const quiet=sim({messages:false,serverNewAt:4*60e3+1});quiet.hot.loop();await quiet.run(4*60e3);
 const before=quiet.reads();assert.ok(before>0&&quiet.armed());await quiet.run(60e3);
 assert.ok(quiet.reads()>before,'cold check discovered the new message');
 const after=quiet.reads();await quiet.run(15e3);assert.equal(quiet.reads(),after+1,'hot mode resumed');
 const dormant=sim({messages:false});dormant.hot.loop();await dormant.run(21*60e3);
 const stopped=dormant.reads();assert.equal(dormant.armed(),false);await dormant.run(5*60e3);
 assert.equal(dormant.reads(),stopped,'cold checks also honor the 20-minute cap');
 dormant.hot.input();assert.equal(dormant.armed(),true);await dormant.run(60e3);
 assert.equal(dormant.reads(),stopped+1,'a tap resumes the cold check');
});

test('full and lite poll reads never overlap, even when a slow lite read is interrupted by focus refresh',async()=>{
 const source=/function createReadGate\(\)\{[\s\S]*?\n\}\}/.exec(js);assert.ok(source,'read gate not found');
 const box={};vm.runInNewContext(source[0]+';this.createReadGate=createReadGate',box);
 const gate=box.createReadGate();let active=0,maxActive=0,fullCalls=0,liteCalls=0,release;
 const slow=new Promise(r=>release=r);
 const lite=gate.lite(async()=>{liteCalls++;active++;maxActive=Math.max(maxActive,active);await slow;active--;return true});
 // Simulates focus or visibility calling full load while hot mode's lite request is still pending.
 const full=gate.full(async()=>{fullCalls++;active++;maxActive=Math.max(maxActive,active);await Promise.resolve();active--;return true});
 assert.equal(await gate.lite(async()=>{throw new Error('busy lite read must be skipped')}),null);
 await Promise.resolve();assert.equal(liteCalls,1);assert.equal(fullCalls,0);
 release();assert.equal(await lite,true);assert.equal(await full,true);
 assert.equal(maxActive,1);assert.equal(liteCalls,1);assert.equal(fullCalls,1);
});

test('first pass read checks account identity before rendering and drops a different-person pass',async()=>{
 const code=[/function clearPass\(\)\{[^\n]*\}/,/function dropPass\(e\)\{[^\n]*\}/,/async function fullRead\(\)\{[\s\S]*?\n\}/]
  .map(re=>{const m=re.exec(js);assert.ok(m,'missing identity guard');return m[0]}).join('\n');
 async function scenario(login){
  const calls=[],adopted=[];const box={Date,API:'/poll',LOGIN_API:'/login',chatCursor:0,lastRead:0,
   history:{state:{filmmaandPollPass:'pass'},replaceState(s){this.state=s}},withPass:v=>v?{filmmaandPollPass:v}:{},
   newKey:()=> 'identity-check-key-0001',hot:{resetFails(){}},adopt:b=>adopted.push(b.source),trouble:e=>{throw e},
   call:async(method,_body,_key,url)=>{calls.push([method,url,box.pass]);if(method==='POST'){if(login instanceof Error)throw login;return login}return {viewer:{name:'Same public name',avatarId:12},source:box.pass?'pass':'session'}}};
  vm.runInNewContext('var pass="pass",autoLogged=false;'+code+';this.run=fullRead',box);
  let failure=null;try{await box.run()}catch(e){failure=e}
  return {calls,adopted,pass:box.pass,state:box.history.state,autoLogged:box.autoLogged,failure};
 }
 const other=await scenario({loggedIn:false,switched:false});
 assert.deepEqual(other.calls.map(([method,url,pass])=>[method,url,pass]),[['GET','/poll','pass'],['POST','/login','pass'],['GET','/poll',null]]);
 assert.deepEqual(other.adopted,['session']);assert.equal(other.pass,null);assert.deepEqual(other.state,{});
 const same=await scenario({loggedIn:true,switched:false});
 assert.deepEqual(same.adopted,['pass']);assert.equal(same.pass,'pass');assert.equal(same.calls.length,2);
 for(const error of [new Error('timeout'),Object.assign(new Error('storage unavailable'),{status:503})]){
  const failed=await scenario(error);
  assert.equal(failed.failure,error);assert.equal(failed.pass,'pass');
  assert.deepEqual(failed.state,{filmmaandPollPass:'pass'});assert.deepEqual(failed.adopted,[]);
 }
});

test('the pass survives a reload via history.state only; never URL, cookie or web storage; cleared when it stops working',()=>{
 const block=js.slice(js.indexOf("const PASS_STATE="),js.indexOf('const hadPass'));
 const clear=/function clearPass\(\)\{[^\n]*\}/.exec(js)[0];
 const drop=/function dropPass\(e\)\{[^\n]*\}/.exec(js)[0];
 function run(href,state){
  const box={URL,history:{state,replaceState(s,_,url){this.state=s;if(url!==undefined)box.location.href=new URL(url,box.location.href).href;this.calls++},calls:0},location:{href},localStorage:null,sessionStorage:null,document:null};
  vm.runInNewContext(block+'\n'+clear+'\n'+drop+'\nthis.get=()=>pass;this.drop=()=>dropPass({code:"pass_invalid"});',box);return box}
 const T='T'.repeat(43);
 const first=run('https://x.test/filmmaand/wanneer/?pas='+T+'&keep=1#h',{other:1});
 assert.equal(first.get(),T);assert.equal(first.location.href,'https://x.test/filmmaand/wanneer/?keep=1#h');
 assert.equal(JSON.stringify(first.history.state),JSON.stringify({other:1,filmmaandPollPass:T}));
 // Reload: same tab state, no ?pas= in the URL.
 const reload=run(first.location.href,first.history.state);assert.equal(reload.get(),T);assert.equal(reload.history.calls,0);
 // pass_invalid clears it from the tab state; the next reload has no pass.
 reload.drop();assert.equal(reload.get(),null);assert.equal(JSON.stringify(reload.history.state),JSON.stringify({other:1}));
 assert.equal(run(reload.location.href,reload.history.state).get(),null);
 // Every replaceState call keeps the URL free of the pass.
 for(const m of js.matchAll(/history\.replaceState\(([^;]*)\)/g))assert.equal(/pas=|pass\b[^S]/.test(m[1].replace(/withPass\((pass|null)\)/,'')),false,m[1]);
});

test('return-to after login: only same-origin /filmmaand/ paths (no open redirect)',async()=>{
 const studio=await readFile(new URL('../public/filmmaand/identity/studio.js',import.meta.url),'utf8');
 const line=/const safeReturn=[^\n]*/.exec(studio)[0];const box={};vm.runInNewContext(line+';this.f=safeReturn',box);
 assert.equal(box.f('/filmmaand/wanneer/'),'/filmmaand/wanneer/');assert.equal(box.f('/filmmaand/programma/'),'/filmmaand/programma/');
 for(const bad of [null,'','/','/filmmaand','//evil.test/filmmaand/','https://evil.test/filmmaand/','/filmmaand//evil.test','/filmmaand/../admin','/filmmaand/%2e%2e/x',
  '/filmmaand/wanneer/?pas=x','/filmmaand/x#y','/filmmaand/\\evil.test','javascript:alert(1)','/filmmaand/ spaced','/Filmmaand/x','/other/','/filmmaand/'+'a'.repeat(100)])
  assert.equal(box.f(bad),null,String(bad));
 assert.match(studio,/location\.replace\(returnTo\|\|'\/filmmaand\/programma\/'/);
 assert.match(js,/\/filmmaand\/identity\/\?terug=\/filmmaand\/wanneer\//);
});

test('mail links and reminder links go to /filmmaand/wanneer/, and the older /filmmaand/?pas= form lands there too',async()=>{
 const r=await handler(new Request('https://ely0030.xyz/filmmaand/?pas=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'),{});
 assert.equal(r.status,302);assert.equal(r.headers.get('location'),'https://ely0030.xyz/filmmaand/wanneer/?pas=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
});

// ---- the API flow, on the real 24–26 Sept manual poll shape
const ORIGIN='https://example.test',NIGHTS=['2026-09-24','2026-09-25','2026-09-26'];
async function fixture(){
 const c=openState(emptyState()),s=createPlanningService({store:c.plans,adminToken:'secret'});
 await s.seed({id:'home-picker-lab',title:'Filmmaand',window:{start:'2026-09-01',end:'2026-09-30'},options:['a','b','c'].map(x=>({id:x,title:x}))});
 const store={data:c.export(),etag:1,async getWithMetadata(){return {data:structuredClone(this.data),etag:String(this.etag)}},async setJSON(k,v,{onlyIfMatch}){if(onlyIfMatch!==String(this.etag))return {modified:false};this.data=structuredClone(v);this.etag++;return {modified:true}}};c.close();
 let code;const api=createApi({store,blobs:{},adminToken:'secret',organizerIds:[],origin:ORIGIN,queueMail:async(c,m)=>{code=m.code},now:()=>'2026-09-23T10:00:00.000Z'});
 async function request(method,body,headers={},path='plans/home-picker-lab/date-poll'){const r=await api(new Request(ORIGIN+'/filmmaand/api/'+path,{method,headers:{Origin:ORIGIN,...headers},...(body?{body:JSON.stringify(body)}:{})}),{ip:'fixture'});return {status:r.status,body:await r.json(),headers:r.headers}}
 const admin=key=>({Authorization:'Bearer secret','Idempotency-Key':key});
 const opened=await request('POST',{action:'open',mode:'availability',pick:'manual',window:{start:NIGHTS[0],end:NIGHTS[2]},choices:[]},admin('open-wanneer-poll-01'));
 assert.equal(opened.status,200,JSON.stringify(opened.body));const pollId=opened.body.datePoll.id;
 // Friends without an account get one at mint time (Contract: `people`).
 const minted=await request('POST',{action:'issue-passes',pollId,people:[{email:'lotte@example.test',name:'Lotte',avatarId:12},{email:'daan@example.test',name:'Daan',avatarId:9},{email:'mo@example.test',name:'Mo',avatarId:7}]},admin('unused-wanneer-00001'));
 assert.equal(minted.status,200,JSON.stringify(minted.body));
 const link=Object.fromEntries(minted.body.passes.map(p=>[p.name,p.url]));
 async function session(email){const ch=await request('POST',{email},{},'auth/code'),r=await request('POST',{challengeId:ch.body.challengeId,code},{},'auth/verify');assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]}
 return {request,pollId,link,session,store};
}
// What wanneer.js does with a mail link: read ?pas= once, then send it as the header.
const passOf=url=>new URL(url).searchParams.get('pas');
const put=(f,pass,revision,yes,key)=>f.request('PUT',{pollId:f.pollId,revision,availability:Object.fromEntries(NIGHTS.map(d=>[d,yes.includes(d)])),favourite:null},{'X-Filmmaand-Poll-Pass':pass,'Content-Type':'application/json','Idempotency-Key':key});

test('mail link → GET → Klaar (PUT) → re-GET shows your own name on the nights you ticked',async()=>{
 const f=await fixture();
 assert.match(f.link.Lotte,/^https:\/\/example\.test\/filmmaand\/wanneer\/\?pas=[A-Za-z0-9_-]{43}$/);
 const lotte=passOf(f.link.Lotte),daan=passOf(f.link.Daan);
 const first=await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte});
 assert.equal(first.status,200);assert.equal(first.headers.get('cache-control'),'private, no-store');
 assert.deepEqual(first.body.viewer,{name:'Lotte',avatarId:12});
 assert.deepEqual(first.body.poll.window,{start:NIGHTS[0],end:NIGHTS[2]});assert.equal(first.body.poll.pick,'manual');assert.equal(first.body.poll.status,'open');
 assert.deepEqual(first.body.availability,{});assert.equal(first.body.revision,0);// not answered: the page shows the untouched poll
 // Invitees: everyone with a live pass, display names only, even before they answer. Date-poll GET only.
 assert.deepEqual(first.body.invitees,['Daan','Lotte','Mo']);
 const pub=await f.request('GET',null,{},'plans/home-picker-lab');assert.equal('invitees' in pub.body,false);assert.equal(JSON.stringify(pub.body).includes('Daan'),false);
 // Daan answered earlier; Lotte sees his name, not her own yet.
 assert.equal((await put(f,daan,0,[NIGHTS[2]],'wanneer-daan-000000001')).status,200);
 const before=(await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte})).body;
 assert.deepEqual(before.poll.ranking.find(r=>r.date===NIGHTS[2]).people,[{name:'Daan',avatarId:9}]);
 // Klaar: every night explicit, favourite null, revision echoed.
 const saved=await put(f,lotte,before.revision,[NIGHTS[0],NIGHTS[2]],'wanneer-lotte-00000001');
 assert.equal(saved.status,200,JSON.stringify(saved.body));assert.equal(saved.body.revision,1);assert.equal('poll' in saved.body,false);
 // An exact retry (same key) replays; the page's network retry reuses its key.
 assert.deepEqual((await put(f,lotte,before.revision,[NIGHTS[0],NIGHTS[2]],'wanneer-lotte-00000001')).body,saved.body);
 const after=(await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte})).body,night=d=>after.poll.ranking.find(r=>r.date===d);
 assert.deepEqual(night(NIGHTS[2]).people,[{name:'Daan',avatarId:9},{name:'Lotte',avatarId:12,self:true}]);
 assert.deepEqual(night(NIGHTS[0]).people,[{name:'Lotte',avatarId:12,self:true}]);
 assert.deepEqual(night(NIGHTS[1]).no,[{name:'Daan',avatarId:9},{name:'Lotte',avatarId:12,self:true}]);
 assert.equal(after.poll.voteCount,2);assert.equal(after.revision,1);
 // Tap-to-change after voting: the next PUT carries the new revision; the stale one is a conflict the page re-GETs through.
 assert.equal((await put(f,lotte,0,[NIGHTS[1]],'wanneer-lotte-00000002')).body.error.code,'revision_conflict');
 assert.equal((await put(f,lotte,1,[NIGHTS[1]],'wanneer-lotte-00000003')).body.revision,2);
 assert.deepEqual((await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte})).body.poll.ranking.find(r=>r.date===NIGHTS[1]).people,[{name:'Lotte',avatarId:12,self:true}]);
});

test('"Ik kan deze week niet" is all false: a saved answer, listed in declined, never reminded',async()=>{
 const f=await fixture(),mo=passOf(f.link.Mo);
 assert.equal((await put(f,mo,0,[],'wanneer-mo-0000000001')).status,200);
 const view=(await f.request('GET',null,{'X-Filmmaand-Poll-Pass':mo})).body;
 assert.deepEqual(view.availability,Object.fromEntries(NIGHTS.map(d=>[d,false])));// the page reads this back as none=true
 assert.deepEqual(view.poll.declined,[{name:'Mo',avatarId:7,self:true}]);assert.equal(view.poll.voteCount,1);
 const nudge=await f.request('POST',{action:'nudge-list',pollId:f.pollId},{Authorization:'Bearer secret'});
 assert.deepEqual(nudge.body.recipients.map(r=>r.name).sort(),['Daan','Lotte']);
});

test('a dead pass is dropped and the session is tried; without a session the page gets a plain 401',async()=>{
 const f=await fixture(),dead='A'.repeat(43);
 const r=await f.request('GET',null,{'X-Filmmaand-Poll-Pass':dead});
 assert.equal(r.status,401);assert.equal(r.body.error.code,'pass_invalid');
 // No pass header, no cookie: 401 (the page shows the calm chip + login link).
 const anon=await f.request('GET');assert.equal(anon.status,401);assert.equal(anon.body.error.code,'unauthorized');// any 401 → the chip
 // With a session (Lotte's account was created at mint time and can log in by email code): the same shape as the pass GET.
 const cookie=await f.session('lotte@example.test'),s=await f.request('GET',null,{Cookie:cookie});
 assert.equal(s.status,200);assert.deepEqual(s.body.viewer,{name:'Lotte',avatarId:12});assert.equal(s.body.pollId,f.pollId);
});

test('the anonymous read (?public=1) is pinned: exact public projection, no names, pass ignored, no writes, no-store',async()=>{
 const f=await fixture(),lotte=passOf(f.link.Lotte);
 await put(f,lotte,0,[NIGHTS[2]],'wanneer-public-000001');await put(f,passOf(f.link.Mo),0,[],'wanneer-public-000002');// a yes and a decline
 const read=h=>f.request('GET',null,h,'plans/home-picker-lab/date-poll?public=1');
 const w=f.store.etag,before=JSON.stringify(f.store.data);
 const anon=await read({});assert.equal(anon.status,200);assert.equal(anon.headers.get('cache-control'),'private, no-store');
 // Exactly this projection, nothing personal: no people/no/declined/invitees/viewer/chat/doodles/rsvp/availability.
 assert.deepEqual(Object.keys(anon.body),['datePoll']);
 assert.deepEqual(Object.keys(anon.body.datePoll).sort(),['choices','closesAt','id','leaderDates','mode','people','pick','ranking','status','voteCount','window']);
 assert.deepEqual(anon.body.datePoll.people,[]);// the legacy single-date field, always empty in availability mode
 for(const r of anon.body.datePoll.ranking)assert.deepEqual(Object.keys(r).sort(),['available','date','favourites','unavailable']);
 const text=JSON.stringify(anon.body);for(const n of ['Lotte','Daan','Mo','Ies'])assert.equal(text.includes(n),false,n);
 assert.equal(anon.body.datePoll.voteCount,2);
 // A pass (valid or dead) is never resolved here: same bytes as anonymous.
 assert.equal(JSON.stringify((await read({'X-Filmmaand-Poll-Pass':lotte})).body),text);
 assert.equal(JSON.stringify((await read({'X-Filmmaand-Poll-Pass':'A'.repeat(43)})).body),text);
 assert.equal((await read({'X-Filmmaand-Poll-Pass':'A'.repeat(43)})).status,200);
 // No writes, however often it is read.
 for(let i=0;i<3;i++)await read({});assert.equal(f.store.etag,w);assert.equal(JSON.stringify(f.store.data),before);
 // Lighter than the public plan GET it replaces for the anonymous view.
 const plan=await f.request('GET',null,{},'plans/home-picker-lab');assert.ok(text.length<JSON.stringify(plan.body).length);
});
