// /filmmaand/wanneer/: the date poll as a group chat. Two halves:
//  1. what ships: generated from the invitation kit, no sample people, no pass leaks, the site's reset guard first;
//  2. the exact API flow the page performs: mail link → pass GET → PUT (Idempotency-Key, revision) → re-GET shows your own
//     name; "Ik kan deze week niet" = all false = declined; a dead pass falls back to the session.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createApi} from './api.mjs';import {openState,emptyState} from './state.mjs';import {createPlanningService} from './runtime/planning/service.mjs';
import handler from './handler.mjs';import vm from 'node:vm';

const dir=new URL('../public/filmmaand/wanneer/',import.meta.url);
const page=await readFile(new URL('index.html',dir),'utf8'),js=await readFile(new URL('wanneer.js',dir),'utf8'),eggs=await readFile(new URL('eggs.js',dir),'utf8');
// The kit's sample people (appje2 CREW) and earlier demo names. None may reach production.
const SAMPLE=['Bas','Koen','Fre','Ruben','Lucas','Joeri','Sjoerd','Noor','Sam','Jules'];

test('the shipped page is the generated kit page, without sample people or kit state',()=>{
 assert.match(page,/^<!doctype html><html lang="nl"><head><script src="\/filmmaand\/identity\/reset-guard.js"><\/script>/);
 assert.match(page,/GENERATED by scripts\/build-wanneer\.mjs/);assert.match(eggs,/^\/\/ GENERATED by scripts\/build-wanneer\.mjs/);
 for(const [name,text] of [['index.html',page],['wanneer.js',js],['eggs.js',eggs]]){
  for(const n of SAMPLE)assert.equal(new RegExp('\\b'+n+'\\b').test(text),false,name+' names '+n);
  assert.equal(/afm-groepsapp|CREW/.test(text),false,name+' carries the kit fixture/state');
  assert.equal(/data:image\/(png|jpe?g|webp);base64/.test(text),false,name+' inlines a raster image');
 }
 assert.match(page,/<span id="sub">Alec, jij<\/span>/);
 // Exactly these scripts, in this order: the guard (head), avatars, the page. eggs.js is started by wanneer.js after the first GET.
 assert.deepEqual([...page.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),['/filmmaand/identity/reset-guard.js','/filmmaand/identity/avatars.js','/filmmaand/wanneer/wanneer.js']);
 assert.equal(/<script>/.test(page),false);
 assert.match(page,/<meta name="referrer" content="no-referrer">/);
 assert.ok(page.includes('#rsvp button[data-pre=true]:not([aria-pressed=true]){border:1.5px dashed #00a884;background:#f0fbf7}'));assert.ok(page.includes('@media (prefers-color-scheme:dark){#rsvp button[data-pre=true]:not([aria-pressed=true]){background:#103529}}'));
 assert.match(js,/Klopt dit\? Tik op je antwoord om het door te geven\./);
 for(const id of ['poll','nights','go','all','none','sys','note','tally','sub','prev','m1','typing','rsvp','rsvp-ja','rsvp-nee','rsvp-sub'])assert.ok(page.includes(`id="${id}"`),id);
 for(const src of page.matchAll(/src="(\/filmmaand\/assets\/[^"]+)"/g))assert.ok(src[1].startsWith('/filmmaand/assets/wanneer-pudding-'));
});

test('the page keeps the pass in memory only and sends it as the header, never in a URL or storage',()=>{
 assert.equal(/localStorage|sessionStorage|document\.cookie|indexedDB/.test(js),false);
 assert.equal(/Authorization|Bearer/.test(js),false);
 assert.match(js,/headers\['X-Filmmaand-Poll-Pass'\]=pass/);
 assert.match(js,/searchParams\.delete\('pas'\);history\.replaceState/);
 // The pass is taken out of the URL before the first request is made.
 assert.ok(js.indexOf("history.replaceState")<js.indexOf('fetch('));
 assert.match(js,/const API='\/filmmaand\/api\/plans\/home-picker-lab\/date-poll'/);
 // The token never goes into a URL: the one fetch goes to the fixed API constant.
 assert.deepEqual(js.match(/fetch\([^,]*,/g),['fetch(url,']);assert.match(js,/async function call\(method,body,key,url=API\)/);
 // URLs: the three fixed endpoints and one numeric chat cursor; nothing else is ever put in a URL.
 assert.deepEqual(js.match(/API\s*\+[^;,)]*/g),["API+'-doodle'","API+'-chat'","API+'-rsvp'","API+'?since='+since:API","API+'?since='+chatCursor"]);
 assert.match(js,/const since=chatCursor;/);assert.match(js,/chatCursor=Math\.max\(chatCursor,c\.cursor\|\|0\)/);
 assert.deepEqual(js.match(/,DOODLE_API\)/g),[',DOODLE_API)']);assert.deepEqual(js.match(/CHAT_API\+'\?since='\+chatCursor\)/g),["CHAT_API+'?since='+chatCursor)"]);
 assert.equal((js.match(/call\('POST'/g)||[]).length,1);// the chat send
 // ?antwoord= only pre-selects: sendRsvp (the only RSVP write) is reached from the two buttons alone.
 assert.deepEqual(js.match(/sendRsvp\(a\)|sendRsvp\(answer,true\)/g),['sendRsvp(answer,true)','sendRsvp(a)']);assert.equal(/preselect[^;\n]*sendRsvp/.test(js),false);
 // Nothing writes on load: the only PUT is inside saveOnce, reached from a tap (Klaar / a night / the quick buttons).
 assert.equal((js.match(/call\('PUT'/g)||[]).length,3);// the vote (saveOnce), the doodle (filmmaandDoodles.save), the rsvp (a tap)
});

test('cadence B: no polling loop; re-GETs only on open, visible/focus (15s), and two bounded ones after a doodle send',()=>{
 // The one interval is the send-button wiggle (UI only). It never requests.
 const intervals=[...js.matchAll(/setInterval\(([^;]*)\)/g)].map(m=>m[1]);
 assert.equal(intervals.length,1);assert.match(intervals[0],/wiggle/);assert.equal(/load\(|call\(|fetch\(/.test(intervals[0]),false);
 // Timed reads: exactly the +20s/+60s pair after a doodle send, only for a visible tab.
 assert.match(js,/\[20e3,60e3\]\.map\(ms=>setTimeout\(\(\)=>\{if\(document\.visibilityState==='visible'/);
 assert.equal((js.match(/setTimeout\([^;]*load\(\)/g)||[]).length,1);
 assert.match(js,/Date\.now\(\)-lastRead<15e3\)return;load\(\)/);
 assert.match(js,/addEventListener\('visibilitychange',fresh\);window\.addEventListener\('focus',fresh\)/);
});

test('the pass survives a reload via history.state only; never URL, cookie or web storage; cleared when it stops working',()=>{
 const block=js.slice(js.indexOf("const PASS_STATE="),js.indexOf('const hadPass'));
 const drop=/function dropPass\(e\)\{[^\n]*\}/.exec(js)[0];
 function run(href,state){
  const box={URL,history:{state,replaceState(s,_,url){this.state=s;if(url!==undefined)box.location.href=new URL(url,box.location.href).href;this.calls++},calls:0},location:{href},localStorage:null,sessionStorage:null,document:null};
  vm.runInNewContext(block+'\n'+drop+'\nthis.get=()=>pass;this.drop=()=>dropPass({code:"pass_invalid"});',box);return box}
 const T='T'.repeat(43);
 const first=run('https://x.test/filmmaand/wanneer/?pas='+T+'&keep=1#h',{other:1});
 assert.equal(first.get(),T);assert.equal(first.location.href,'https://x.test/filmmaand/wanneer/?keep=1#h');
 assert.equal(JSON.stringify(first.history.state),JSON.stringify({other:1,filmmaandPollPass:T}));
 // Reload: same tab state, no ?pas= in the URL.
 const reload=run(first.location.href,first.history.state);assert.equal(reload.get(),T);assert.equal(reload.history.calls,0);
 // pass_invalid clears it from the tab state; the next reload has no pass.
 reload.drop();assert.equal(reload.get(),null);assert.equal(JSON.stringify(reload.history.state),JSON.stringify({other:1}));
 assert.equal(run(reload.location.href,reload.history.state).get(),null);
 // Every replaceState call keeps the URL free of the pass.
 for(const m of js.matchAll(/history\.replaceState\(([^;]*)\)/g))assert.equal(/pas=|pass\b[^S]/.test(m[1].replace(/withPass\((pass|null)\)/,'')),false,m[1]);
});

test('return-to after login: only same-origin /filmmaand/ paths (no open redirect)',async()=>{
 const studio=await readFile(new URL('../public/filmmaand/identity/studio.js',import.meta.url),'utf8');
 const line=/const safeReturn=[^\n]*/.exec(studio)[0];const box={};vm.runInNewContext(line+';this.f=safeReturn',box);
 assert.equal(box.f('/filmmaand/wanneer/'),'/filmmaand/wanneer/');assert.equal(box.f('/filmmaand/programma/'),'/filmmaand/programma/');
 for(const bad of [null,'','/','/filmmaand','//evil.test/filmmaand/','https://evil.test/filmmaand/','/filmmaand//evil.test','/filmmaand/../admin','/filmmaand/%2e%2e/x',
  '/filmmaand/wanneer/?pas=x','/filmmaand/x#y','/filmmaand/\\evil.test','javascript:alert(1)','/filmmaand/ spaced','/Filmmaand/x','/other/','/filmmaand/'+'a'.repeat(100)])
  assert.equal(box.f(bad),null,String(bad));
 assert.match(studio,/location\.replace\(returnTo\|\|'\/filmmaand\/programma\/'/);
 assert.match(js,/\/filmmaand\/identity\/\?terug=\/filmmaand\/wanneer\//);
});

test('mail links and reminder links go to /filmmaand/wanneer/, and the older /filmmaand/?pas= form lands there too',async()=>{
 const r=await handler(new Request('https://ely0030.xyz/filmmaand/?pas=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'),{});
 assert.equal(r.status,302);assert.equal(r.headers.get('location'),'https://ely0030.xyz/filmmaand/wanneer/?pas=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
});

// ---- the API flow, on the real 24–26 Sept manual poll shape
const ORIGIN='https://example.test',NIGHTS=['2026-09-24','2026-09-25','2026-09-26'];
async function fixture(){
 const c=openState(emptyState()),s=createPlanningService({store:c.plans,adminToken:'secret'});
 await s.seed({id:'home-picker-lab',title:'Filmmaand',window:{start:'2026-09-01',end:'2026-09-30'},options:['a','b','c'].map(x=>({id:x,title:x}))});
 const store={data:c.export(),etag:1,async getWithMetadata(){return {data:structuredClone(this.data),etag:String(this.etag)}},async setJSON(k,v,{onlyIfMatch}){if(onlyIfMatch!==String(this.etag))return {modified:false};this.data=structuredClone(v);this.etag++;return {modified:true}}};c.close();
 let code;const api=createApi({store,blobs:{},adminToken:'secret',organizerIds:[],origin:ORIGIN,queueMail:async(c,m)=>{code=m.code},now:()=>'2026-09-23T10:00:00.000Z'});
 async function request(method,body,headers={},path='plans/home-picker-lab/date-poll'){const r=await api(new Request(ORIGIN+'/filmmaand/api/'+path,{method,headers:{Origin:ORIGIN,...headers},...(body?{body:JSON.stringify(body)}:{})}),{ip:'fixture'});return {status:r.status,body:await r.json(),headers:r.headers}}
 const admin=key=>({Authorization:'Bearer secret','Idempotency-Key':key});
 const opened=await request('POST',{action:'open',mode:'availability',pick:'manual',window:{start:NIGHTS[0],end:NIGHTS[2]},choices:[]},admin('open-wanneer-poll-01'));
 assert.equal(opened.status,200,JSON.stringify(opened.body));const pollId=opened.body.datePoll.id;
 // Friends without an account get one at mint time (Contract: `people`).
 const minted=await request('POST',{action:'issue-passes',pollId,people:[{email:'lotte@example.test',name:'Lotte',avatarId:12},{email:'daan@example.test',name:'Daan',avatarId:9},{email:'mo@example.test',name:'Mo',avatarId:7}]},admin('unused-wanneer-00001'));
 assert.equal(minted.status,200,JSON.stringify(minted.body));
 const link=Object.fromEntries(minted.body.passes.map(p=>[p.name,p.url]));
 async function session(email){const ch=await request('POST',{email},{},'auth/code'),r=await request('POST',{challengeId:ch.body.challengeId,code},{},'auth/verify');assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]}
 return {request,pollId,link,session};
}
// What wanneer.js does with a mail link: read ?pas= once, then send it as the header.
const passOf=url=>new URL(url).searchParams.get('pas');
const put=(f,pass,revision,yes,key)=>f.request('PUT',{pollId:f.pollId,revision,availability:Object.fromEntries(NIGHTS.map(d=>[d,yes.includes(d)])),favourite:null},{'X-Filmmaand-Poll-Pass':pass,'Content-Type':'application/json','Idempotency-Key':key});

test('mail link → GET → Klaar (PUT) → re-GET shows your own name on the nights you ticked',async()=>{
 const f=await fixture();
 assert.match(f.link.Lotte,/^https:\/\/example\.test\/filmmaand\/wanneer\/\?pas=[A-Za-z0-9_-]{43}$/);
 const lotte=passOf(f.link.Lotte),daan=passOf(f.link.Daan);
 const first=await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte});
 assert.equal(first.status,200);assert.equal(first.headers.get('cache-control'),'private, no-store');
 assert.deepEqual(first.body.viewer,{name:'Lotte',avatarId:12});
 assert.deepEqual(first.body.poll.window,{start:NIGHTS[0],end:NIGHTS[2]});assert.equal(first.body.poll.pick,'manual');assert.equal(first.body.poll.status,'open');
 assert.deepEqual(first.body.availability,{});assert.equal(first.body.revision,0);// not answered: the page shows the untouched poll
 // Invitees: everyone with a live pass, display names only, even before they answer. Date-poll GET only.
 assert.deepEqual(first.body.invitees,['Daan','Lotte','Mo']);
 const pub=await f.request('GET',null,{},'plans/home-picker-lab');assert.equal('invitees' in pub.body,false);assert.equal(JSON.stringify(pub.body).includes('Daan'),false);
 // Daan answered earlier; Lotte sees his name, not her own yet.
 assert.equal((await put(f,daan,0,[NIGHTS[2]],'wanneer-daan-000000001')).status,200);
 const before=(await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte})).body;
 assert.deepEqual(before.poll.ranking.find(r=>r.date===NIGHTS[2]).people,[{name:'Daan',avatarId:9}]);
 // Klaar: every night explicit, favourite null, revision echoed.
 const saved=await put(f,lotte,before.revision,[NIGHTS[0],NIGHTS[2]],'wanneer-lotte-00000001');
 assert.equal(saved.status,200,JSON.stringify(saved.body));assert.equal(saved.body.revision,1);assert.equal('poll' in saved.body,false);
 // An exact retry (same key) replays; the page's network retry reuses its key.
 assert.deepEqual((await put(f,lotte,before.revision,[NIGHTS[0],NIGHTS[2]],'wanneer-lotte-00000001')).body,saved.body);
 const after=(await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte})).body,night=d=>after.poll.ranking.find(r=>r.date===d);
 assert.deepEqual(night(NIGHTS[2]).people,[{name:'Daan',avatarId:9},{name:'Lotte',avatarId:12,self:true}]);
 assert.deepEqual(night(NIGHTS[0]).people,[{name:'Lotte',avatarId:12,self:true}]);
 assert.deepEqual(night(NIGHTS[1]).no,[{name:'Daan',avatarId:9},{name:'Lotte',avatarId:12,self:true}]);
 assert.equal(after.poll.voteCount,2);assert.equal(after.revision,1);
 // Tap-to-change after voting: the next PUT carries the new revision; the stale one is a conflict the page re-GETs through.
 assert.equal((await put(f,lotte,0,[NIGHTS[1]],'wanneer-lotte-00000002')).body.error.code,'revision_conflict');
 assert.equal((await put(f,lotte,1,[NIGHTS[1]],'wanneer-lotte-00000003')).body.revision,2);
 assert.deepEqual((await f.request('GET',null,{'X-Filmmaand-Poll-Pass':lotte})).body.poll.ranking.find(r=>r.date===NIGHTS[1]).people,[{name:'Lotte',avatarId:12,self:true}]);
});

test('"Ik kan deze week niet" is all false: a saved answer, listed in declined, never reminded',async()=>{
 const f=await fixture(),mo=passOf(f.link.Mo);
 assert.equal((await put(f,mo,0,[],'wanneer-mo-0000000001')).status,200);
 const view=(await f.request('GET',null,{'X-Filmmaand-Poll-Pass':mo})).body;
 assert.deepEqual(view.availability,Object.fromEntries(NIGHTS.map(d=>[d,false])));// the page reads this back as none=true
 assert.deepEqual(view.poll.declined,[{name:'Mo',avatarId:7,self:true}]);assert.equal(view.poll.voteCount,1);
 const nudge=await f.request('POST',{action:'nudge-list',pollId:f.pollId},{Authorization:'Bearer secret'});
 assert.deepEqual(nudge.body.recipients.map(r=>r.name).sort(),['Daan','Lotte']);
});

test('a dead pass is dropped and the session is tried; without a session the page gets a plain 401',async()=>{
 const f=await fixture(),dead='A'.repeat(43);
 const r=await f.request('GET',null,{'X-Filmmaand-Poll-Pass':dead});
 assert.equal(r.status,401);assert.equal(r.body.error.code,'pass_invalid');
 // No pass header, no cookie: 401 (the page shows the calm chip + login link).
 const anon=await f.request('GET');assert.equal(anon.status,401);assert.equal(anon.body.error.code,'unauthorized');// any 401 → the chip
 // With a session (Lotte's account was created at mint time and can log in by email code): the same shape as the pass GET.
 const cookie=await f.session('lotte@example.test'),s=await f.request('GET',null,{Cookie:cookie});
 assert.equal(s.status,200);assert.deepEqual(s.body.viewer,{name:'Lotte',avatarId:12});assert.equal(s.body.pollId,f.pollId);
});
